
namespace EFRET_TMS
{
    partial class ActiveUsersUC
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.radGridView1 = new Telerik.WinControls.UI.RadGridView();
            this.tmsLocks = new EFRET_TMS.tmsLocks();
            this.tmsLocksBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.syslocksBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.sys_locksTableAdapter = new EFRET_TMS.tmsLocksTableAdapters.sys_locksTableAdapter();
            this.toastNotificationsManager1 = new DevExpress.XtraBars.ToastNotifications.ToastNotificationsManager(this.components);
            this.radThemeManager1 = new Telerik.WinControls.RadThemeManager();
            this.office2019DarkTheme1 = new Telerik.WinControls.Themes.Office2019DarkTheme();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tmsLocks)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tmsLocksBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.syslocksBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.toastNotificationsManager1)).BeginInit();
            this.SuspendLayout();
            // 
            // radGridView1
            // 
            this.radGridView1.AutoGenerateHierarchy = true;
            this.radGridView1.BackColor = System.Drawing.SystemColors.Control;
            this.radGridView1.Cursor = System.Windows.Forms.Cursors.Default;
            this.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radGridView1.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.radGridView1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radGridView1.Location = new System.Drawing.Point(0, 0);
            // 
            // 
            // 
            this.radGridView1.MasterTemplate.AddNewRowPosition = Telerik.WinControls.UI.SystemRowPosition.Bottom;
            this.radGridView1.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewTextBoxColumn1.FieldName = "userName";
            gridViewTextBoxColumn1.HeaderText = "userName";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "userName";
            gridViewTextBoxColumn1.Width = 114;
            gridViewTextBoxColumn2.FieldName = "workstationID";
            gridViewTextBoxColumn2.HeaderText = "workstationID";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "workstationID";
            gridViewTextBoxColumn2.Width = 114;
            gridViewTextBoxColumn3.FieldName = "activeSession";
            gridViewTextBoxColumn3.HeaderText = "activeSession";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "activeSession";
            gridViewTextBoxColumn3.Width = 114;
            gridViewTextBoxColumn4.FieldName = "currentProcess";
            gridViewTextBoxColumn4.HeaderText = "currentProcess";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "currentProcess";
            gridViewTextBoxColumn4.Width = 114;
            this.radGridView1.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4});
            this.radGridView1.MasterTemplate.DataSource = this.syslocksBindingSource;
            this.radGridView1.MasterTemplate.EnableAlternatingRowColor = true;
            this.radGridView1.MasterTemplate.EnableGrouping = false;
            this.radGridView1.MasterTemplate.EnablePaging = true;
            this.radGridView1.MasterTemplate.SelectionMode = Telerik.WinControls.UI.GridViewSelectionMode.CellSelect;
            this.radGridView1.MasterTemplate.ShowFilteringRow = false;
            this.radGridView1.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.radGridView1.Name = "radGridView1";
            this.radGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radGridView1.ShowGroupPanel = false;
            this.radGridView1.ShowGroupPanelScrollbars = false;
            this.radGridView1.Size = new System.Drawing.Size(476, 391);
            this.radGridView1.TabIndex = 0;
            this.radGridView1.ThemeName = "Office2019Dark";
            this.radGridView1.Click += new System.EventHandler(this.radGridView1_Click);
            // 
            // tmsLocks
            // 
            this.tmsLocks.DataSetName = "tmsLocks";
            this.tmsLocks.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // tmsLocksBindingSource
            // 
            this.tmsLocksBindingSource.DataSource = this.tmsLocks;
            this.tmsLocksBindingSource.Position = 0;
            // 
            // syslocksBindingSource
            // 
            this.syslocksBindingSource.DataMember = "sys_locks";
            this.syslocksBindingSource.DataSource = this.tmsLocksBindingSource;
            // 
            // sys_locksTableAdapter
            // 
            this.sys_locksTableAdapter.ClearBeforeFill = true;
            // 
            // toastNotificationsManager1
            // 
            this.toastNotificationsManager1.ApplicationId = "86fffaa1-22d0-4074-b8f0-2a23be463307";
            this.toastNotificationsManager1.Notifications.AddRange(new DevExpress.XtraBars.ToastNotifications.IToastNotificationProperties[] {
            new DevExpress.XtraBars.ToastNotifications.ToastNotification("690dd219-6b14-4ad5-be71-34acb45781d6", null, "User Administration", "Please inform the user that you are disconnecting them before you action any even" +
                    "ts here.", "All actions are irreversable.", DevExpress.XtraBars.ToastNotifications.ToastNotificationTemplate.ImageAndText04),
            new DevExpress.XtraBars.ToastNotifications.ToastNotification("b0e0af89-4fba-48df-9057-685cab77d4ff", null, "Pellentesque lacinia tellus eget volutpat", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i" +
                    "ncididunt ut labore et dolore magna aliqua.", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i" +
                    "ncididunt ut labore et dolore magna aliqua.", DevExpress.XtraBars.ToastNotifications.ToastNotificationTemplate.Text01)});
            // 
            // ActiveUsersUC
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.radGridView1);
            this.Name = "ActiveUsersUC";
            this.Size = new System.Drawing.Size(476, 391);
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tmsLocks)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tmsLocksBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.syslocksBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.toastNotificationsManager1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView radGridView1;
        private tmsLocks tmsLocks;
        private System.Windows.Forms.BindingSource tmsLocksBindingSource;
        private System.Windows.Forms.BindingSource syslocksBindingSource;
        private tmsLocksTableAdapters.sys_locksTableAdapter sys_locksTableAdapter;
        private DevExpress.XtraBars.ToastNotifications.ToastNotificationsManager toastNotificationsManager1;
        private Telerik.WinControls.RadThemeManager radThemeManager1;
        private Telerik.WinControls.Themes.Office2019DarkTheme office2019DarkTheme1;
    }
}
