
CREATE VIEW [Movement_xpoView] AS
	SELECT
		[idMovement] AS XpoIdentityColumn,
		[IdCO],
		[Contractualdate],
		[ContractualTime],
		[EffectiveDate],
		[EffectiveTime],
		[CompletedDate],
		[CompletedTime],
		[Operation],
		[companyCode],
		[KM],
		[Cost],
		[Currency],
		[CostVATCode],
		[DateCreation],
		[UserCreation],
		[CostProvider],
		[CostProviderFerry],
		[Done],
		[MvtSpecialInstruction],
		[MvtBookingNeeded],
		[MvtReference],
		[MvtComment],
		[VehicleDetails],
		[DriverName],
		[DriverMobilPhone],
		[NumberOfDriver],
		[TractorNumber],
		[Mvtcontact],
		[MvtEmail],
		[MvtTelephone],
		[MvtMobile],
		[CPSpecialInstruction],
		[CPPaymentTerms],
		[CPEOM],
		[CodeRoute],
		[CodeMichelin1],
		[CodeMichelin2],
		[CarrierInfo],
		[Cancellation],
		[HotelPark],
		[Redirection],
		[Toll],
		[DemurageLoading],
		[DemurageDelivery],
		[BasicCost],
		[CustomClearence],
		[P44StatusCode],
		[P44ArrivalCode],
		[P44Arrival],
		[P44Departure],
		[P44ETAStart],
		[P44ETAEnd],
		[P44Override],
		[P44ETAUpdate]
	FROM [Movement]
GO
CREATE PROCEDURE [sp_Movement_xpoView_insert]
	@XpoIdentityColumn int OUT,
	@IdCO int = null,
	@Contractualdate datetime,
	@ContractualTime datetime,
	@EffectiveDate datetime,
	@EffectiveTime datetime,
	@CompletedDate datetime,
	@CompletedTime datetime,
	@Operation nvarchar(255),
	@companyCode nvarchar(6),
	@KM float,
	@Cost float,
	@Currency nvarchar(255),
	@CostVATCode nvarchar(3),
	@DateCreation datetime,
	@UserCreation nvarchar(50),
	@CostProvider nvarchar(6),
	@CostProviderFerry nvarchar(6),
	@Done bit,
	@MvtSpecialInstruction nvarchar(200),
	@MvtBookingNeeded bit,
	@MvtReference nvarchar(50),
	@MvtComment nvarchar(255),
	@VehicleDetails nvarchar(50),
	@DriverName nvarchar(30),
	@DriverMobilPhone nvarchar(15),
	@NumberOfDriver smallint,
	@TractorNumber nvarchar(30),
	@Mvtcontact nvarchar(50),
	@MvtEmail nvarchar(200),
	@MvtTelephone nvarchar(25),
	@MvtMobile nvarchar(25),
	@CPSpecialInstruction nvarchar(255),
	@CPPaymentTerms smallint,
	@CPEOM bit,
	@CodeRoute nvarchar(6),
	@CodeMichelin1 nvarchar(10),
	@CodeMichelin2 nvarchar(10),
	@CarrierInfo bit,
	@Cancellation money,
	@HotelPark money,
	@Redirection money,
	@Toll money,
	@DemurageLoading money,
	@DemurageDelivery money,
	@BasicCost money,
	@CustomClearence money,
	@P44StatusCode nvarchar(255),
	@P44ArrivalCode nvarchar(255),
	@P44Arrival datetime,
	@P44Departure datetime,
	@P44ETAStart datetime,
	@P44ETAEnd datetime,
	@P44Override bit,
	@P44ETAUpdate datetime
AS
BEGIN
	BEGIN TRY
		INSERT INTO [Movement](
			[IdCO],
			[Contractualdate],
			[ContractualTime],
			[EffectiveDate],
			[EffectiveTime],
			[CompletedDate],
			[CompletedTime],
			[Operation],
			[companyCode],
			[KM],
			[Cost],
			[Currency],
			[CostVATCode],
			[DateCreation],
			[UserCreation],
			[CostProvider],
			[CostProviderFerry],
			[Done],
			[MvtSpecialInstruction],
			[MvtBookingNeeded],
			[MvtReference],
			[MvtComment],
			[VehicleDetails],
			[DriverName],
			[DriverMobilPhone],
			[NumberOfDriver],
			[TractorNumber],
			[Mvtcontact],
			[MvtEmail],
			[MvtTelephone],
			[MvtMobile],
			[CPSpecialInstruction],
			[CPPaymentTerms],
			[CPEOM],
			[CodeRoute],
			[CodeMichelin1],
			[CodeMichelin2],
			[CarrierInfo],
			[Cancellation],
			[HotelPark],
			[Redirection],
			[Toll],
			[DemurageLoading],
			[DemurageDelivery],
			[BasicCost],
			[CustomClearence],
			[P44StatusCode],
			[P44ArrivalCode],
			[P44Arrival],
			[P44Departure],
			[P44ETAStart],
			[P44ETAEnd],
			[P44Override],
			[P44ETAUpdate]
		)
		VALUES(
			@IdCO,
			@Contractualdate,
			@ContractualTime,
			@EffectiveDate,
			@EffectiveTime,
			@CompletedDate,
			@CompletedTime,
			@Operation,
			@companyCode,
			@KM,
			@Cost,
			@Currency,
			@CostVATCode,
			@DateCreation,
			@UserCreation,
			@CostProvider,
			@CostProviderFerry,
			@Done,
			@MvtSpecialInstruction,
			@MvtBookingNeeded,
			@MvtReference,
			@MvtComment,
			@VehicleDetails,
			@DriverName,
			@DriverMobilPhone,
			@NumberOfDriver,
			@TractorNumber,
			@Mvtcontact,
			@MvtEmail,
			@MvtTelephone,
			@MvtMobile,
			@CPSpecialInstruction,
			@CPPaymentTerms,
			@CPEOM,
			@CodeRoute,
			@CodeMichelin1,
			@CodeMichelin2,
			@CarrierInfo,
			@Cancellation,
			@HotelPark,
			@Redirection,
			@Toll,
			@DemurageLoading,
			@DemurageDelivery,
			@BasicCost,
			@CustomClearence,
			@P44StatusCode,
			@P44ArrivalCode,
			@P44Arrival,
			@P44Departure,
			@P44ETAStart,
			@P44ETAEnd,
			@P44Override,
			@P44ETAUpdate
		);
		SET @XpoIdentityColumn = SCOPE_IDENTITY();
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		SELECT @ErrorMessage = ERROR_MESSAGE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();
		RAISERROR(
			@ErrorMessage,
			@ErrorSeverity,
			@ErrorState
		);
	END CATCH
END
GO
CREATE PROCEDURE [sp_Movement_xpoView_update]
	@idMovement int,
	@old_IdCO int,
	@IdCO int,
	@old_Contractualdate datetime,
	@Contractualdate datetime,
	@old_ContractualTime datetime,
	@ContractualTime datetime,
	@old_EffectiveDate datetime,
	@EffectiveDate datetime,
	@old_EffectiveTime datetime,
	@EffectiveTime datetime,
	@old_CompletedDate datetime,
	@CompletedDate datetime,
	@old_CompletedTime datetime,
	@CompletedTime datetime,
	@old_Operation nvarchar(255),
	@Operation nvarchar(255),
	@old_companyCode nvarchar(6),
	@companyCode nvarchar(6),
	@old_KM float,
	@KM float,
	@old_Cost float,
	@Cost float,
	@old_Currency nvarchar(255),
	@Currency nvarchar(255),
	@old_CostVATCode nvarchar(3),
	@CostVATCode nvarchar(3),
	@old_DateCreation datetime,
	@DateCreation datetime,
	@old_UserCreation nvarchar(50),
	@UserCreation nvarchar(50),
	@old_CostProvider nvarchar(6),
	@CostProvider nvarchar(6),
	@old_CostProviderFerry nvarchar(6),
	@CostProviderFerry nvarchar(6),
	@old_Done bit,
	@Done bit,
	@old_MvtSpecialInstruction nvarchar(200),
	@MvtSpecialInstruction nvarchar(200),
	@old_MvtBookingNeeded bit,
	@MvtBookingNeeded bit,
	@old_MvtReference nvarchar(50),
	@MvtReference nvarchar(50),
	@old_MvtComment nvarchar(255),
	@MvtComment nvarchar(255),
	@old_VehicleDetails nvarchar(50),
	@VehicleDetails nvarchar(50),
	@old_DriverName nvarchar(30),
	@DriverName nvarchar(30),
	@old_DriverMobilPhone nvarchar(15),
	@DriverMobilPhone nvarchar(15),
	@old_NumberOfDriver smallint,
	@NumberOfDriver smallint,
	@old_TractorNumber nvarchar(30),
	@TractorNumber nvarchar(30),
	@old_Mvtcontact nvarchar(50),
	@Mvtcontact nvarchar(50),
	@old_MvtEmail nvarchar(200),
	@MvtEmail nvarchar(200),
	@old_MvtTelephone nvarchar(25),
	@MvtTelephone nvarchar(25),
	@old_MvtMobile nvarchar(25),
	@MvtMobile nvarchar(25),
	@old_CPSpecialInstruction nvarchar(255),
	@CPSpecialInstruction nvarchar(255),
	@old_CPPaymentTerms smallint,
	@CPPaymentTerms smallint,
	@old_CPEOM bit,
	@CPEOM bit,
	@old_CodeRoute nvarchar(6),
	@CodeRoute nvarchar(6),
	@old_CodeMichelin1 nvarchar(10),
	@CodeMichelin1 nvarchar(10),
	@old_CodeMichelin2 nvarchar(10),
	@CodeMichelin2 nvarchar(10),
	@old_CarrierInfo bit,
	@CarrierInfo bit,
	@old_Cancellation money,
	@Cancellation money,
	@old_HotelPark money,
	@HotelPark money,
	@old_Redirection money,
	@Redirection money,
	@old_Toll money,
	@Toll money,
	@old_DemurageLoading money,
	@DemurageLoading money,
	@old_DemurageDelivery money,
	@DemurageDelivery money,
	@old_BasicCost money,
	@BasicCost money,
	@old_CustomClearence money,
	@CustomClearence money,
	@old_P44StatusCode nvarchar(255),
	@P44StatusCode nvarchar(255),
	@old_P44ArrivalCode nvarchar(255),
	@P44ArrivalCode nvarchar(255),
	@old_P44Arrival datetime,
	@P44Arrival datetime,
	@old_P44Departure datetime,
	@P44Departure datetime,
	@old_P44ETAStart datetime,
	@P44ETAStart datetime,
	@old_P44ETAEnd datetime,
	@P44ETAEnd datetime,
	@old_P44Override bit,
	@P44Override bit,
	@old_P44ETAUpdate datetime,
	@P44ETAUpdate datetime
AS
	UPDATE [Movement] SET
		[IdCO]=@IdCO,
		[Contractualdate]=@Contractualdate,
		[ContractualTime]=@ContractualTime,
		[EffectiveDate]=@EffectiveDate,
		[EffectiveTime]=@EffectiveTime,
		[CompletedDate]=@CompletedDate,
		[CompletedTime]=@CompletedTime,
		[Operation]=@Operation,
		[companyCode]=@companyCode,
		[KM]=@KM,
		[Cost]=@Cost,
		[Currency]=@Currency,
		[CostVATCode]=@CostVATCode,
		[DateCreation]=@DateCreation,
		[UserCreation]=@UserCreation,
		[CostProvider]=@CostProvider,
		[CostProviderFerry]=@CostProviderFerry,
		[Done]=@Done,
		[MvtSpecialInstruction]=@MvtSpecialInstruction,
		[MvtBookingNeeded]=@MvtBookingNeeded,
		[MvtReference]=@MvtReference,
		[MvtComment]=@MvtComment,
		[VehicleDetails]=@VehicleDetails,
		[DriverName]=@DriverName,
		[DriverMobilPhone]=@DriverMobilPhone,
		[NumberOfDriver]=@NumberOfDriver,
		[TractorNumber]=@TractorNumber,
		[Mvtcontact]=@Mvtcontact,
		[MvtEmail]=@MvtEmail,
		[MvtTelephone]=@MvtTelephone,
		[MvtMobile]=@MvtMobile,
		[CPSpecialInstruction]=@CPSpecialInstruction,
		[CPPaymentTerms]=@CPPaymentTerms,
		[CPEOM]=@CPEOM,
		[CodeRoute]=@CodeRoute,
		[CodeMichelin1]=@CodeMichelin1,
		[CodeMichelin2]=@CodeMichelin2,
		[CarrierInfo]=@CarrierInfo,
		[Cancellation]=@Cancellation,
		[HotelPark]=@HotelPark,
		[Redirection]=@Redirection,
		[Toll]=@Toll,
		[DemurageLoading]=@DemurageLoading,
		[DemurageDelivery]=@DemurageDelivery,
		[BasicCost]=@BasicCost,
		[CustomClearence]=@CustomClearence,
		[P44StatusCode]=@P44StatusCode,
		[P44ArrivalCode]=@P44ArrivalCode,
		[P44Arrival]=@P44Arrival,
		[P44Departure]=@P44Departure,
		[P44ETAStart]=@P44ETAStart,
		[P44ETAEnd]=@P44ETAEnd,
		[P44Override]=@P44Override,
		[P44ETAUpdate]=@P44ETAUpdate
	WHERE
		[idMovement] = @idMovement
GO
CREATE PROCEDURE [sp_Movement_xpoView_delete]
	@idMovement int,
	@old_IdCO int,
	@old_Contractualdate datetime,
	@old_ContractualTime datetime,
	@old_EffectiveDate datetime,
	@old_EffectiveTime datetime,
	@old_CompletedDate datetime,
	@old_CompletedTime datetime,
	@old_Operation nvarchar(255),
	@old_companyCode nvarchar(6),
	@old_KM float,
	@old_Cost float,
	@old_Currency nvarchar(255),
	@old_CostVATCode nvarchar(3),
	@old_DateCreation datetime,
	@old_UserCreation nvarchar(50),
	@old_CostProvider nvarchar(6),
	@old_CostProviderFerry nvarchar(6),
	@old_Done bit,
	@old_MvtSpecialInstruction nvarchar(200),
	@old_MvtBookingNeeded bit,
	@old_MvtReference nvarchar(50),
	@old_MvtComment nvarchar(255),
	@old_VehicleDetails nvarchar(50),
	@old_DriverName nvarchar(30),
	@old_DriverMobilPhone nvarchar(15),
	@old_NumberOfDriver smallint,
	@old_TractorNumber nvarchar(30),
	@old_Mvtcontact nvarchar(50),
	@old_MvtEmail nvarchar(200),
	@old_MvtTelephone nvarchar(25),
	@old_MvtMobile nvarchar(25),
	@old_CPSpecialInstruction nvarchar(255),
	@old_CPPaymentTerms smallint,
	@old_CPEOM bit,
	@old_CodeRoute nvarchar(6),
	@old_CodeMichelin1 nvarchar(10),
	@old_CodeMichelin2 nvarchar(10),
	@old_CarrierInfo bit,
	@old_Cancellation money,
	@old_HotelPark money,
	@old_Redirection money,
	@old_Toll money,
	@old_DemurageLoading money,
	@old_DemurageDelivery money,
	@old_BasicCost money,
	@old_CustomClearence money,
	@old_P44StatusCode nvarchar(255),
	@old_P44ArrivalCode nvarchar(255),
	@old_P44Arrival datetime,
	@old_P44Departure datetime,
	@old_P44ETAStart datetime,
	@old_P44ETAEnd datetime,
	@old_P44Override bit,
	@old_P44ETAUpdate datetime
AS
	DELETE FROM [Movement] WHERE
		[idMovement] = @idMovement
GO
CREATE TRIGGER [t_Movement_xpoView_insert]
ON [Movement_xpoView]
INSTEAD OF INSERT AS
BEGIN
	RAISERROR('Use sp_Movement_xpoView_insert instead', 16, 1, null);
END
GO
CREATE TRIGGER [t_Movement_xpoView_update]
ON [Movement_xpoView]
INSTEAD OF UPDATE AS
BEGIN
	DECLARE @cur CURSOR
	SET @cur = CURSOR FOR
		SELECT
			i.[XpoIdentityColumn],
			d.[IdCO] as [old_IdCO],
			i.[IdCO],
			d.[Contractualdate] as [old_Contractualdate],
			i.[Contractualdate],
			d.[ContractualTime] as [old_ContractualTime],
			i.[ContractualTime],
			d.[EffectiveDate] as [old_EffectiveDate],
			i.[EffectiveDate],
			d.[EffectiveTime] as [old_EffectiveTime],
			i.[EffectiveTime],
			d.[CompletedDate] as [old_CompletedDate],
			i.[CompletedDate],
			d.[CompletedTime] as [old_CompletedTime],
			i.[CompletedTime],
			d.[Operation] as [old_Operation],
			i.[Operation],
			d.[companyCode] as [old_companyCode],
			i.[companyCode],
			d.[KM] as [old_KM],
			i.[KM],
			d.[Cost] as [old_Cost],
			i.[Cost],
			d.[Currency] as [old_Currency],
			i.[Currency],
			d.[CostVATCode] as [old_CostVATCode],
			i.[CostVATCode],
			d.[DateCreation] as [old_DateCreation],
			i.[DateCreation],
			d.[UserCreation] as [old_UserCreation],
			i.[UserCreation],
			d.[CostProvider] as [old_CostProvider],
			i.[CostProvider],
			d.[CostProviderFerry] as [old_CostProviderFerry],
			i.[CostProviderFerry],
			d.[Done] as [old_Done],
			i.[Done],
			d.[MvtSpecialInstruction] as [old_MvtSpecialInstruction],
			i.[MvtSpecialInstruction],
			d.[MvtBookingNeeded] as [old_MvtBookingNeeded],
			i.[MvtBookingNeeded],
			d.[MvtReference] as [old_MvtReference],
			i.[MvtReference],
			d.[MvtComment] as [old_MvtComment],
			i.[MvtComment],
			d.[VehicleDetails] as [old_VehicleDetails],
			i.[VehicleDetails],
			d.[DriverName] as [old_DriverName],
			i.[DriverName],
			d.[DriverMobilPhone] as [old_DriverMobilPhone],
			i.[DriverMobilPhone],
			d.[NumberOfDriver] as [old_NumberOfDriver],
			i.[NumberOfDriver],
			d.[TractorNumber] as [old_TractorNumber],
			i.[TractorNumber],
			d.[Mvtcontact] as [old_Mvtcontact],
			i.[Mvtcontact],
			d.[MvtEmail] as [old_MvtEmail],
			i.[MvtEmail],
			d.[MvtTelephone] as [old_MvtTelephone],
			i.[MvtTelephone],
			d.[MvtMobile] as [old_MvtMobile],
			i.[MvtMobile],
			d.[CPSpecialInstruction] as [old_CPSpecialInstruction],
			i.[CPSpecialInstruction],
			d.[CPPaymentTerms] as [old_CPPaymentTerms],
			i.[CPPaymentTerms],
			d.[CPEOM] as [old_CPEOM],
			i.[CPEOM],
			d.[CodeRoute] as [old_CodeRoute],
			i.[CodeRoute],
			d.[CodeMichelin1] as [old_CodeMichelin1],
			i.[CodeMichelin1],
			d.[CodeMichelin2] as [old_CodeMichelin2],
			i.[CodeMichelin2],
			d.[CarrierInfo] as [old_CarrierInfo],
			i.[CarrierInfo],
			d.[Cancellation] as [old_Cancellation],
			i.[Cancellation],
			d.[HotelPark] as [old_HotelPark],
			i.[HotelPark],
			d.[Redirection] as [old_Redirection],
			i.[Redirection],
			d.[Toll] as [old_Toll],
			i.[Toll],
			d.[DemurageLoading] as [old_DemurageLoading],
			i.[DemurageLoading],
			d.[DemurageDelivery] as [old_DemurageDelivery],
			i.[DemurageDelivery],
			d.[BasicCost] as [old_BasicCost],
			i.[BasicCost],
			d.[CustomClearence] as [old_CustomClearence],
			i.[CustomClearence],
			d.[P44StatusCode] as [old_P44StatusCode],
			i.[P44StatusCode],
			d.[P44ArrivalCode] as [old_P44ArrivalCode],
			i.[P44ArrivalCode],
			d.[P44Arrival] as [old_P44Arrival],
			i.[P44Arrival],
			d.[P44Departure] as [old_P44Departure],
			i.[P44Departure],
			d.[P44ETAStart] as [old_P44ETAStart],
			i.[P44ETAStart],
			d.[P44ETAEnd] as [old_P44ETAEnd],
			i.[P44ETAEnd],
			d.[P44Override] as [old_P44Override],
			i.[P44Override],
			d.[P44ETAUpdate] as [old_P44ETAUpdate],
			i.[P44ETAUpdate]
		FROM
			inserted i
			INNER JOIN
			deleted d
			ON
				i.[XpoIdentityColumn] = d.[XpoIdentityColumn]
	OPEN @cur
	DECLARE @XpoIdentityColumn int
	DECLARE @old_IdCO int
	DECLARE @IdCO int
	DECLARE @old_Contractualdate datetime
	DECLARE @Contractualdate datetime
	DECLARE @old_ContractualTime datetime
	DECLARE @ContractualTime datetime
	DECLARE @old_EffectiveDate datetime
	DECLARE @EffectiveDate datetime
	DECLARE @old_EffectiveTime datetime
	DECLARE @EffectiveTime datetime
	DECLARE @old_CompletedDate datetime
	DECLARE @CompletedDate datetime
	DECLARE @old_CompletedTime datetime
	DECLARE @CompletedTime datetime
	DECLARE @old_Operation nvarchar(255)
	DECLARE @Operation nvarchar(255)
	DECLARE @old_companyCode nvarchar(6)
	DECLARE @companyCode nvarchar(6)
	DECLARE @old_KM float
	DECLARE @KM float
	DECLARE @old_Cost float
	DECLARE @Cost float
	DECLARE @old_Currency nvarchar(255)
	DECLARE @Currency nvarchar(255)
	DECLARE @old_CostVATCode nvarchar(3)
	DECLARE @CostVATCode nvarchar(3)
	DECLARE @old_DateCreation datetime
	DECLARE @DateCreation datetime
	DECLARE @old_UserCreation nvarchar(50)
	DECLARE @UserCreation nvarchar(50)
	DECLARE @old_CostProvider nvarchar(6)
	DECLARE @CostProvider nvarchar(6)
	DECLARE @old_CostProviderFerry nvarchar(6)
	DECLARE @CostProviderFerry nvarchar(6)
	DECLARE @old_Done bit
	DECLARE @Done bit
	DECLARE @old_MvtSpecialInstruction nvarchar(200)
	DECLARE @MvtSpecialInstruction nvarchar(200)
	DECLARE @old_MvtBookingNeeded bit
	DECLARE @MvtBookingNeeded bit
	DECLARE @old_MvtReference nvarchar(50)
	DECLARE @MvtReference nvarchar(50)
	DECLARE @old_MvtComment nvarchar(255)
	DECLARE @MvtComment nvarchar(255)
	DECLARE @old_VehicleDetails nvarchar(50)
	DECLARE @VehicleDetails nvarchar(50)
	DECLARE @old_DriverName nvarchar(30)
	DECLARE @DriverName nvarchar(30)
	DECLARE @old_DriverMobilPhone nvarchar(15)
	DECLARE @DriverMobilPhone nvarchar(15)
	DECLARE @old_NumberOfDriver smallint
	DECLARE @NumberOfDriver smallint
	DECLARE @old_TractorNumber nvarchar(30)
	DECLARE @TractorNumber nvarchar(30)
	DECLARE @old_Mvtcontact nvarchar(50)
	DECLARE @Mvtcontact nvarchar(50)
	DECLARE @old_MvtEmail nvarchar(200)
	DECLARE @MvtEmail nvarchar(200)
	DECLARE @old_MvtTelephone nvarchar(25)
	DECLARE @MvtTelephone nvarchar(25)
	DECLARE @old_MvtMobile nvarchar(25)
	DECLARE @MvtMobile nvarchar(25)
	DECLARE @old_CPSpecialInstruction nvarchar(255)
	DECLARE @CPSpecialInstruction nvarchar(255)
	DECLARE @old_CPPaymentTerms smallint
	DECLARE @CPPaymentTerms smallint
	DECLARE @old_CPEOM bit
	DECLARE @CPEOM bit
	DECLARE @old_CodeRoute nvarchar(6)
	DECLARE @CodeRoute nvarchar(6)
	DECLARE @old_CodeMichelin1 nvarchar(10)
	DECLARE @CodeMichelin1 nvarchar(10)
	DECLARE @old_CodeMichelin2 nvarchar(10)
	DECLARE @CodeMichelin2 nvarchar(10)
	DECLARE @old_CarrierInfo bit
	DECLARE @CarrierInfo bit
	DECLARE @old_Cancellation money
	DECLARE @Cancellation money
	DECLARE @old_HotelPark money
	DECLARE @HotelPark money
	DECLARE @old_Redirection money
	DECLARE @Redirection money
	DECLARE @old_Toll money
	DECLARE @Toll money
	DECLARE @old_DemurageLoading money
	DECLARE @DemurageLoading money
	DECLARE @old_DemurageDelivery money
	DECLARE @DemurageDelivery money
	DECLARE @old_BasicCost money
	DECLARE @BasicCost money
	DECLARE @old_CustomClearence money
	DECLARE @CustomClearence money
	DECLARE @old_P44StatusCode nvarchar(255)
	DECLARE @P44StatusCode nvarchar(255)
	DECLARE @old_P44ArrivalCode nvarchar(255)
	DECLARE @P44ArrivalCode nvarchar(255)
	DECLARE @old_P44Arrival datetime
	DECLARE @P44Arrival datetime
	DECLARE @old_P44Departure datetime
	DECLARE @P44Departure datetime
	DECLARE @old_P44ETAStart datetime
	DECLARE @P44ETAStart datetime
	DECLARE @old_P44ETAEnd datetime
	DECLARE @P44ETAEnd datetime
	DECLARE @old_P44Override bit
	DECLARE @P44Override bit
	DECLARE @old_P44ETAUpdate datetime
	DECLARE @P44ETAUpdate datetime
	FETCH NEXT FROM @cur INTO
		@XpoIdentityColumn,
		@old_IdCO,
		@IdCO,
		@old_Contractualdate,
		@Contractualdate,
		@old_ContractualTime,
		@ContractualTime,
		@old_EffectiveDate,
		@EffectiveDate,
		@old_EffectiveTime,
		@EffectiveTime,
		@old_CompletedDate,
		@CompletedDate,
		@old_CompletedTime,
		@CompletedTime,
		@old_Operation,
		@Operation,
		@old_companyCode,
		@companyCode,
		@old_KM,
		@KM,
		@old_Cost,
		@Cost,
		@old_Currency,
		@Currency,
		@old_CostVATCode,
		@CostVATCode,
		@old_DateCreation,
		@DateCreation,
		@old_UserCreation,
		@UserCreation,
		@old_CostProvider,
		@CostProvider,
		@old_CostProviderFerry,
		@CostProviderFerry,
		@old_Done,
		@Done,
		@old_MvtSpecialInstruction,
		@MvtSpecialInstruction,
		@old_MvtBookingNeeded,
		@MvtBookingNeeded,
		@old_MvtReference,
		@MvtReference,
		@old_MvtComment,
		@MvtComment,
		@old_VehicleDetails,
		@VehicleDetails,
		@old_DriverName,
		@DriverName,
		@old_DriverMobilPhone,
		@DriverMobilPhone,
		@old_NumberOfDriver,
		@NumberOfDriver,
		@old_TractorNumber,
		@TractorNumber,
		@old_Mvtcontact,
		@Mvtcontact,
		@old_MvtEmail,
		@MvtEmail,
		@old_MvtTelephone,
		@MvtTelephone,
		@old_MvtMobile,
		@MvtMobile,
		@old_CPSpecialInstruction,
		@CPSpecialInstruction,
		@old_CPPaymentTerms,
		@CPPaymentTerms,
		@old_CPEOM,
		@CPEOM,
		@old_CodeRoute,
		@CodeRoute,
		@old_CodeMichelin1,
		@CodeMichelin1,
		@old_CodeMichelin2,
		@CodeMichelin2,
		@old_CarrierInfo,
		@CarrierInfo,
		@old_Cancellation,
		@Cancellation,
		@old_HotelPark,
		@HotelPark,
		@old_Redirection,
		@Redirection,
		@old_Toll,
		@Toll,
		@old_DemurageLoading,
		@DemurageLoading,
		@old_DemurageDelivery,
		@DemurageDelivery,
		@old_BasicCost,
		@BasicCost,
		@old_CustomClearence,
		@CustomClearence,
		@old_P44StatusCode,
		@P44StatusCode,
		@old_P44ArrivalCode,
		@P44ArrivalCode,
		@old_P44Arrival,
		@P44Arrival,
		@old_P44Departure,
		@P44Departure,
		@old_P44ETAStart,
		@P44ETAStart,
		@old_P44ETAEnd,
		@P44ETAEnd,
		@old_P44Override,
		@P44Override,
		@old_P44ETAUpdate,
		@P44ETAUpdate
	WHILE(@@fetch_status <> -1)
	BEGIN
		EXEC [sp_Movement_xpoView_update]
			@XpoIdentityColumn,
			@old_IdCO,
			@IdCO,
			@old_Contractualdate,
			@Contractualdate,
			@old_ContractualTime,
			@ContractualTime,
			@old_EffectiveDate,
			@EffectiveDate,
			@old_EffectiveTime,
			@EffectiveTime,
			@old_CompletedDate,
			@CompletedDate,
			@old_CompletedTime,
			@CompletedTime,
			@old_Operation,
			@Operation,
			@old_companyCode,
			@companyCode,
			@old_KM,
			@KM,
			@old_Cost,
			@Cost,
			@old_Currency,
			@Currency,
			@old_CostVATCode,
			@CostVATCode,
			@old_DateCreation,
			@DateCreation,
			@old_UserCreation,
			@UserCreation,
			@old_CostProvider,
			@CostProvider,
			@old_CostProviderFerry,
			@CostProviderFerry,
			@old_Done,
			@Done,
			@old_MvtSpecialInstruction,
			@MvtSpecialInstruction,
			@old_MvtBookingNeeded,
			@MvtBookingNeeded,
			@old_MvtReference,
			@MvtReference,
			@old_MvtComment,
			@MvtComment,
			@old_VehicleDetails,
			@VehicleDetails,
			@old_DriverName,
			@DriverName,
			@old_DriverMobilPhone,
			@DriverMobilPhone,
			@old_NumberOfDriver,
			@NumberOfDriver,
			@old_TractorNumber,
			@TractorNumber,
			@old_Mvtcontact,
			@Mvtcontact,
			@old_MvtEmail,
			@MvtEmail,
			@old_MvtTelephone,
			@MvtTelephone,
			@old_MvtMobile,
			@MvtMobile,
			@old_CPSpecialInstruction,
			@CPSpecialInstruction,
			@old_CPPaymentTerms,
			@CPPaymentTerms,
			@old_CPEOM,
			@CPEOM,
			@old_CodeRoute,
			@CodeRoute,
			@old_CodeMichelin1,
			@CodeMichelin1,
			@old_CodeMichelin2,
			@CodeMichelin2,
			@old_CarrierInfo,
			@CarrierInfo,
			@old_Cancellation,
			@Cancellation,
			@old_HotelPark,
			@HotelPark,
			@old_Redirection,
			@Redirection,
			@old_Toll,
			@Toll,
			@old_DemurageLoading,
			@DemurageLoading,
			@old_DemurageDelivery,
			@DemurageDelivery,
			@old_BasicCost,
			@BasicCost,
			@old_CustomClearence,
			@CustomClearence,
			@old_P44StatusCode,
			@P44StatusCode,
			@old_P44ArrivalCode,
			@P44ArrivalCode,
			@old_P44Arrival,
			@P44Arrival,
			@old_P44Departure,
			@P44Departure,
			@old_P44ETAStart,
			@P44ETAStart,
			@old_P44ETAEnd,
			@P44ETAEnd,
			@old_P44Override,
			@P44Override,
			@old_P44ETAUpdate,
			@P44ETAUpdate
		FETCH NEXT FROM @cur INTO
			@XpoIdentityColumn,
			@old_IdCO,
			@IdCO,
			@old_Contractualdate,
			@Contractualdate,
			@old_ContractualTime,
			@ContractualTime,
			@old_EffectiveDate,
			@EffectiveDate,
			@old_EffectiveTime,
			@EffectiveTime,
			@old_CompletedDate,
			@CompletedDate,
			@old_CompletedTime,
			@CompletedTime,
			@old_Operation,
			@Operation,
			@old_companyCode,
			@companyCode,
			@old_KM,
			@KM,
			@old_Cost,
			@Cost,
			@old_Currency,
			@Currency,
			@old_CostVATCode,
			@CostVATCode,
			@old_DateCreation,
			@DateCreation,
			@old_UserCreation,
			@UserCreation,
			@old_CostProvider,
			@CostProvider,
			@old_CostProviderFerry,
			@CostProviderFerry,
			@old_Done,
			@Done,
			@old_MvtSpecialInstruction,
			@MvtSpecialInstruction,
			@old_MvtBookingNeeded,
			@MvtBookingNeeded,
			@old_MvtReference,
			@MvtReference,
			@old_MvtComment,
			@MvtComment,
			@old_VehicleDetails,
			@VehicleDetails,
			@old_DriverName,
			@DriverName,
			@old_DriverMobilPhone,
			@DriverMobilPhone,
			@old_NumberOfDriver,
			@NumberOfDriver,
			@old_TractorNumber,
			@TractorNumber,
			@old_Mvtcontact,
			@Mvtcontact,
			@old_MvtEmail,
			@MvtEmail,
			@old_MvtTelephone,
			@MvtTelephone,
			@old_MvtMobile,
			@MvtMobile,
			@old_CPSpecialInstruction,
			@CPSpecialInstruction,
			@old_CPPaymentTerms,
			@CPPaymentTerms,
			@old_CPEOM,
			@CPEOM,
			@old_CodeRoute,
			@CodeRoute,
			@old_CodeMichelin1,
			@CodeMichelin1,
			@old_CodeMichelin2,
			@CodeMichelin2,
			@old_CarrierInfo,
			@CarrierInfo,
			@old_Cancellation,
			@Cancellation,
			@old_HotelPark,
			@HotelPark,
			@old_Redirection,
			@Redirection,
			@old_Toll,
			@Toll,
			@old_DemurageLoading,
			@DemurageLoading,
			@old_DemurageDelivery,
			@DemurageDelivery,
			@old_BasicCost,
			@BasicCost,
			@old_CustomClearence,
			@CustomClearence,
			@old_P44StatusCode,
			@P44StatusCode,
			@old_P44ArrivalCode,
			@P44ArrivalCode,
			@old_P44Arrival,
			@P44Arrival,
			@old_P44Departure,
			@P44Departure,
			@old_P44ETAStart,
			@P44ETAStart,
			@old_P44ETAEnd,
			@P44ETAEnd,
			@old_P44Override,
			@P44Override,
			@old_P44ETAUpdate,
			@P44ETAUpdate
	END
	CLOSE @cur
	DEALLOCATE @cur
END
GO
CREATE TRIGGER [t_Movement_xpoView_delete]
ON [Movement_xpoView]
INSTEAD OF DELETE AS
BEGIN
	DECLARE @cur CURSOR
	SET @cur = CURSOR FOR
		SELECT
			[XpoIdentityColumn],
			[IdCO],
			[Contractualdate],
			[ContractualTime],
			[EffectiveDate],
			[EffectiveTime],
			[CompletedDate],
			[CompletedTime],
			[Operation],
			[companyCode],
			[KM],
			[Cost],
			[Currency],
			[CostVATCode],
			[DateCreation],
			[UserCreation],
			[CostProvider],
			[CostProviderFerry],
			[Done],
			[MvtSpecialInstruction],
			[MvtBookingNeeded],
			[MvtReference],
			[MvtComment],
			[VehicleDetails],
			[DriverName],
			[DriverMobilPhone],
			[NumberOfDriver],
			[TractorNumber],
			[Mvtcontact],
			[MvtEmail],
			[MvtTelephone],
			[MvtMobile],
			[CPSpecialInstruction],
			[CPPaymentTerms],
			[CPEOM],
			[CodeRoute],
			[CodeMichelin1],
			[CodeMichelin2],
			[CarrierInfo],
			[Cancellation],
			[HotelPark],
			[Redirection],
			[Toll],
			[DemurageLoading],
			[DemurageDelivery],
			[BasicCost],
			[CustomClearence],
			[P44StatusCode],
			[P44ArrivalCode],
			[P44Arrival],
			[P44Departure],
			[P44ETAStart],
			[P44ETAEnd],
			[P44Override],
			[P44ETAUpdate]
		FROM deleted
	OPEN @cur
	DECLARE @XpoIdentityColumn int
	DECLARE @IdCO int
	DECLARE @Contractualdate datetime
	DECLARE @ContractualTime datetime
	DECLARE @EffectiveDate datetime
	DECLARE @EffectiveTime datetime
	DECLARE @CompletedDate datetime
	DECLARE @CompletedTime datetime
	DECLARE @Operation nvarchar(255)
	DECLARE @companyCode nvarchar(6)
	DECLARE @KM float
	DECLARE @Cost float
	DECLARE @Currency nvarchar(255)
	DECLARE @CostVATCode nvarchar(3)
	DECLARE @DateCreation datetime
	DECLARE @UserCreation nvarchar(50)
	DECLARE @CostProvider nvarchar(6)
	DECLARE @CostProviderFerry nvarchar(6)
	DECLARE @Done bit
	DECLARE @MvtSpecialInstruction nvarchar(200)
	DECLARE @MvtBookingNeeded bit
	DECLARE @MvtReference nvarchar(50)
	DECLARE @MvtComment nvarchar(255)
	DECLARE @VehicleDetails nvarchar(50)
	DECLARE @DriverName nvarchar(30)
	DECLARE @DriverMobilPhone nvarchar(15)
	DECLARE @NumberOfDriver smallint
	DECLARE @TractorNumber nvarchar(30)
	DECLARE @Mvtcontact nvarchar(50)
	DECLARE @MvtEmail nvarchar(200)
	DECLARE @MvtTelephone nvarchar(25)
	DECLARE @MvtMobile nvarchar(25)
	DECLARE @CPSpecialInstruction nvarchar(255)
	DECLARE @CPPaymentTerms smallint
	DECLARE @CPEOM bit
	DECLARE @CodeRoute nvarchar(6)
	DECLARE @CodeMichelin1 nvarchar(10)
	DECLARE @CodeMichelin2 nvarchar(10)
	DECLARE @CarrierInfo bit
	DECLARE @Cancellation money
	DECLARE @HotelPark money
	DECLARE @Redirection money
	DECLARE @Toll money
	DECLARE @DemurageLoading money
	DECLARE @DemurageDelivery money
	DECLARE @BasicCost money
	DECLARE @CustomClearence money
	DECLARE @P44StatusCode nvarchar(255)
	DECLARE @P44ArrivalCode nvarchar(255)
	DECLARE @P44Arrival datetime
	DECLARE @P44Departure datetime
	DECLARE @P44ETAStart datetime
	DECLARE @P44ETAEnd datetime
	DECLARE @P44Override bit
	DECLARE @P44ETAUpdate datetime
	FETCH NEXT FROM @cur INTO
		@XpoIdentityColumn,
		@IdCO,
		@Contractualdate,
		@ContractualTime,
		@EffectiveDate,
		@EffectiveTime,
		@CompletedDate,
		@CompletedTime,
		@Operation,
		@companyCode,
		@KM,
		@Cost,
		@Currency,
		@CostVATCode,
		@DateCreation,
		@UserCreation,
		@CostProvider,
		@CostProviderFerry,
		@Done,
		@MvtSpecialInstruction,
		@MvtBookingNeeded,
		@MvtReference,
		@MvtComment,
		@VehicleDetails,
		@DriverName,
		@DriverMobilPhone,
		@NumberOfDriver,
		@TractorNumber,
		@Mvtcontact,
		@MvtEmail,
		@MvtTelephone,
		@MvtMobile,
		@CPSpecialInstruction,
		@CPPaymentTerms,
		@CPEOM,
		@CodeRoute,
		@CodeMichelin1,
		@CodeMichelin2,
		@CarrierInfo,
		@Cancellation,
		@HotelPark,
		@Redirection,
		@Toll,
		@DemurageLoading,
		@DemurageDelivery,
		@BasicCost,
		@CustomClearence,
		@P44StatusCode,
		@P44ArrivalCode,
		@P44Arrival,
		@P44Departure,
		@P44ETAStart,
		@P44ETAEnd,
		@P44Override,
		@P44ETAUpdate
	WHILE(@@fetch_status <> -1)
	BEGIN
		EXEC [sp_Movement_xpoView_delete]
			@XpoIdentityColumn,
			@IdCO,
			@Contractualdate,
			@ContractualTime,
			@EffectiveDate,
			@EffectiveTime,
			@CompletedDate,
			@CompletedTime,
			@Operation,
			@companyCode,
			@KM,
			@Cost,
			@Currency,
			@CostVATCode,
			@DateCreation,
			@UserCreation,
			@CostProvider,
			@CostProviderFerry,
			@Done,
			@MvtSpecialInstruction,
			@MvtBookingNeeded,
			@MvtReference,
			@MvtComment,
			@VehicleDetails,
			@DriverName,
			@DriverMobilPhone,
			@NumberOfDriver,
			@TractorNumber,
			@Mvtcontact,
			@MvtEmail,
			@MvtTelephone,
			@MvtMobile,
			@CPSpecialInstruction,
			@CPPaymentTerms,
			@CPEOM,
			@CodeRoute,
			@CodeMichelin1,
			@CodeMichelin2,
			@CarrierInfo,
			@Cancellation,
			@HotelPark,
			@Redirection,
			@Toll,
			@DemurageLoading,
			@DemurageDelivery,
			@BasicCost,
			@CustomClearence,
			@P44StatusCode,
			@P44ArrivalCode,
			@P44Arrival,
			@P44Departure,
			@P44ETAStart,
			@P44ETAEnd,
			@P44Override,
			@P44ETAUpdate
		FETCH NEXT FROM @cur INTO
			@XpoIdentityColumn,
			@IdCO,
			@Contractualdate,
			@ContractualTime,
			@EffectiveDate,
			@EffectiveTime,
			@CompletedDate,
			@CompletedTime,
			@Operation,
			@companyCode,
			@KM,
			@Cost,
			@Currency,
			@CostVATCode,
			@DateCreation,
			@UserCreation,
			@CostProvider,
			@CostProviderFerry,
			@Done,
			@MvtSpecialInstruction,
			@MvtBookingNeeded,
			@MvtReference,
			@MvtComment,
			@VehicleDetails,
			@DriverName,
			@DriverMobilPhone,
			@NumberOfDriver,
			@TractorNumber,
			@Mvtcontact,
			@MvtEmail,
			@MvtTelephone,
			@MvtMobile,
			@CPSpecialInstruction,
			@CPPaymentTerms,
			@CPEOM,
			@CodeRoute,
			@CodeMichelin1,
			@CodeMichelin2,
			@CarrierInfo,
			@Cancellation,
			@HotelPark,
			@Redirection,
			@Toll,
			@DemurageLoading,
			@DemurageDelivery,
			@BasicCost,
			@CustomClearence,
			@P44StatusCode,
			@P44ArrivalCode,
			@P44Arrival,
			@P44Departure,
			@P44ETAStart,
			@P44ETAEnd,
			@P44Override,
			@P44ETAUpdate
	END
	CLOSE @cur
	DEALLOCATE @cur
END
GO

CREATE VIEW [NewCO_xpoView] AS
	SELECT
		[IdCO] AS XpoIdentityColumn,
		[NewCO],
		[DateCreation],
		[DateUpdate],
		[IdContractHolder],
		[ContractHolderReference],
		[CMR],
		[SalesPrice],
		[ConversionRate],
		[SalesPriceCurrency],
		[SalesPriceInCurrency],
		[SalesPriceVATCode],
		[SalesPriceVATRate],
		[SalesPriceVATAmount],
		[ContractHolderPaymentTerm],
		[ContractHolderPaymentTermOEM],
		[Comment],
		[InvoiceInGBP],
		[AllRisksInsurance],
		[ContractHolderEmail],
		[ContractHolderTel],
		[ContractHolderMob],
		[TrailerNumber],
		[TrailerTypeAutorised],
		[InterModal],
		[Invoiced],
		[UserCreation],
		[UserUpdate],
		[UserOwner],
		[Actif],
		[Xroute],
		[TripType2],
		[BaseFreightRate],
		[FuelSurcharge],
		[StopOver1],
		[StopOver2],
		[FuelSurchargeRate],
		[AdhocRate],
		[demurrage],
		[DemurageCode],
		[InvoiceNumber],
		[InvoiceDate],
		[InvoicePath],
		[Line],
		[InvoiceEDI],
		[ShipperAccount],
		[ReroutingSurcharge],
		[Wharehousing],
		[Redelivery],
		[Cancellation],
		[BillingAccount],
		[AdHocSurcharge],
		[DriverDententionAtUnloading],
		[eShipCo],
		[Corridor],
		[CoS],
		[CustomClearance],
		[P44ToUpload],
		[P44Uploaded],
		[P44ShipmentID],
		[P44LastUpdate],
		[P44StatusCode],
		[P44ReasonCode],
		[P44ReasonDescription],
		[P44TrackTrailer],
		[P44TrackingStarted],
		[P44TrackingCompleted],
		[P44TrackingError],
		[P44UploadError],
		[P44Latitude],
		[P44Longitude],
		[P44CurrentStop]
	FROM [NewCO]
GO
CREATE PROCEDURE [sp_NewCO_xpoView_insert]
	@XpoIdentityColumn int OUT,
	@NewCO nvarchar(50),
	@DateCreation datetime,
	@DateUpdate datetime,
	@IdContractHolder nvarchar(6),
	@ContractHolderReference nvarchar(50),
	@CMR bit,
	@SalesPrice float,
	@ConversionRate float,
	@SalesPriceCurrency nvarchar(1),
	@SalesPriceInCurrency float,
	@SalesPriceVATCode nvarchar(3),
	@SalesPriceVATRate float,
	@SalesPriceVATAmount float,
	@ContractHolderPaymentTerm nvarchar(50),
	@ContractHolderPaymentTermOEM bit,
	@Comment nvarchar(255),
	@InvoiceInGBP float,
	@AllRisksInsurance nvarchar(3),
	@ContractHolderEmail nvarchar(50),
	@ContractHolderTel nvarchar(25),
	@ContractHolderMob nvarchar(25),
	@TrailerNumber nvarchar(30),
	@TrailerTypeAutorised nvarchar(50),
	@InterModal bit,
	@Invoiced bit,
	@UserCreation nvarchar(50),
	@UserUpdate nvarchar(50),
	@UserOwner nvarchar(50),
	@Actif bit,
	@Xroute bit,
	@TripType2 nvarchar(10),
	@BaseFreightRate float,
	@FuelSurcharge float,
	@StopOver1 nvarchar(20),
	@StopOver2 nvarchar(20),
	@FuelSurchargeRate float,
	@AdhocRate float,
	@demurrage float,
	@DemurageCode nvarchar(20),
	@InvoiceNumber int,
	@InvoiceDate datetime,
	@InvoicePath nvarchar(50),
	@Line nvarchar(255),
	@InvoiceEDI nvarchar(50),
	@ShipperAccount nvarchar(255),
	@ReroutingSurcharge float,
	@Wharehousing float,
	@Redelivery float,
	@Cancellation float,
	@BillingAccount nvarchar(30),
	@AdHocSurcharge float,
	@DriverDententionAtUnloading float,
	@eShipCo smallint,
	@Corridor nvarchar(50),
	@CoS bit,
	@CustomClearance money,
	@P44ToUpload bit,
	@P44Uploaded bit,
	@P44ShipmentID double precision,
	@P44LastUpdate datetime,
	@P44StatusCode nvarchar(255),
	@P44ReasonCode nvarchar(255),
	@P44ReasonDescription nvarchar(255),
	@P44TrackTrailer bit,
	@P44TrackingStarted bit,
	@P44TrackingCompleted bit,
	@P44TrackingError bit,
	@P44UploadError bit,
	@P44Latitude float,
	@P44Longitude float,
	@P44CurrentStop int
AS
BEGIN
	BEGIN TRY
		INSERT INTO [NewCO](
			[NewCO],
			[DateCreation],
			[DateUpdate],
			[IdContractHolder],
			[ContractHolderReference],
			[CMR],
			[SalesPrice],
			[ConversionRate],
			[SalesPriceCurrency],
			[SalesPriceInCurrency],
			[SalesPriceVATCode],
			[SalesPriceVATRate],
			[SalesPriceVATAmount],
			[ContractHolderPaymentTerm],
			[ContractHolderPaymentTermOEM],
			[Comment],
			[InvoiceInGBP],
			[AllRisksInsurance],
			[ContractHolderEmail],
			[ContractHolderTel],
			[ContractHolderMob],
			[TrailerNumber],
			[TrailerTypeAutorised],
			[InterModal],
			[Invoiced],
			[UserCreation],
			[UserUpdate],
			[UserOwner],
			[Actif],
			[Xroute],
			[TripType2],
			[BaseFreightRate],
			[FuelSurcharge],
			[StopOver1],
			[StopOver2],
			[FuelSurchargeRate],
			[AdhocRate],
			[demurrage],
			[DemurageCode],
			[InvoiceNumber],
			[InvoiceDate],
			[InvoicePath],
			[Line],
			[InvoiceEDI],
			[ShipperAccount],
			[ReroutingSurcharge],
			[Wharehousing],
			[Redelivery],
			[Cancellation],
			[BillingAccount],
			[AdHocSurcharge],
			[DriverDententionAtUnloading],
			[eShipCo],
			[Corridor],
			[CoS],
			[CustomClearance],
			[P44ToUpload],
			[P44Uploaded],
			[P44ShipmentID],
			[P44LastUpdate],
			[P44StatusCode],
			[P44ReasonCode],
			[P44ReasonDescription],
			[P44TrackTrailer],
			[P44TrackingStarted],
			[P44TrackingCompleted],
			[P44TrackingError],
			[P44UploadError],
			[P44Latitude],
			[P44Longitude],
			[P44CurrentStop]
		)
		VALUES(
			@NewCO,
			@DateCreation,
			@DateUpdate,
			@IdContractHolder,
			@ContractHolderReference,
			@CMR,
			@SalesPrice,
			@ConversionRate,
			@SalesPriceCurrency,
			@SalesPriceInCurrency,
			@SalesPriceVATCode,
			@SalesPriceVATRate,
			@SalesPriceVATAmount,
			@ContractHolderPaymentTerm,
			@ContractHolderPaymentTermOEM,
			@Comment,
			@InvoiceInGBP,
			@AllRisksInsurance,
			@ContractHolderEmail,
			@ContractHolderTel,
			@ContractHolderMob,
			@TrailerNumber,
			@TrailerTypeAutorised,
			@InterModal,
			@Invoiced,
			@UserCreation,
			@UserUpdate,
			@UserOwner,
			@Actif,
			@Xroute,
			@TripType2,
			@BaseFreightRate,
			@FuelSurcharge,
			@StopOver1,
			@StopOver2,
			@FuelSurchargeRate,
			@AdhocRate,
			@demurrage,
			@DemurageCode,
			@InvoiceNumber,
			@InvoiceDate,
			@InvoicePath,
			@Line,
			@InvoiceEDI,
			@ShipperAccount,
			@ReroutingSurcharge,
			@Wharehousing,
			@Redelivery,
			@Cancellation,
			@BillingAccount,
			@AdHocSurcharge,
			@DriverDententionAtUnloading,
			@eShipCo,
			@Corridor,
			@CoS,
			@CustomClearance,
			@P44ToUpload,
			@P44Uploaded,
			@P44ShipmentID,
			@P44LastUpdate,
			@P44StatusCode,
			@P44ReasonCode,
			@P44ReasonDescription,
			@P44TrackTrailer,
			@P44TrackingStarted,
			@P44TrackingCompleted,
			@P44TrackingError,
			@P44UploadError,
			@P44Latitude,
			@P44Longitude,
			@P44CurrentStop
		);
		SET @XpoIdentityColumn = SCOPE_IDENTITY();
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		SELECT @ErrorMessage = ERROR_MESSAGE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();
		RAISERROR(
			@ErrorMessage,
			@ErrorSeverity,
			@ErrorState
		);
	END CATCH
END
GO
CREATE PROCEDURE [sp_NewCO_xpoView_update]
	@IdCO int,
	@old_NewCO nvarchar(50),
	@NewCO nvarchar(50),
	@old_DateCreation datetime,
	@DateCreation datetime,
	@old_DateUpdate datetime,
	@DateUpdate datetime,
	@old_IdContractHolder nvarchar(6),
	@IdContractHolder nvarchar(6),
	@old_ContractHolderReference nvarchar(50),
	@ContractHolderReference nvarchar(50),
	@old_CMR bit,
	@CMR bit,
	@old_SalesPrice float,
	@SalesPrice float,
	@old_ConversionRate float,
	@ConversionRate float,
	@old_SalesPriceCurrency nvarchar(1),
	@SalesPriceCurrency nvarchar(1),
	@old_SalesPriceInCurrency float,
	@SalesPriceInCurrency float,
	@old_SalesPriceVATCode nvarchar(3),
	@SalesPriceVATCode nvarchar(3),
	@old_SalesPriceVATRate float,
	@SalesPriceVATRate float,
	@old_SalesPriceVATAmount float,
	@SalesPriceVATAmount float,
	@old_ContractHolderPaymentTerm nvarchar(50),
	@ContractHolderPaymentTerm nvarchar(50),
	@old_ContractHolderPaymentTermOEM bit,
	@ContractHolderPaymentTermOEM bit,
	@old_Comment nvarchar(255),
	@Comment nvarchar(255),
	@old_InvoiceInGBP float,
	@InvoiceInGBP float,
	@old_AllRisksInsurance nvarchar(3),
	@AllRisksInsurance nvarchar(3),
	@old_ContractHolderEmail nvarchar(50),
	@ContractHolderEmail nvarchar(50),
	@old_ContractHolderTel nvarchar(25),
	@ContractHolderTel nvarchar(25),
	@old_ContractHolderMob nvarchar(25),
	@ContractHolderMob nvarchar(25),
	@old_TrailerNumber nvarchar(30),
	@TrailerNumber nvarchar(30),
	@old_TrailerTypeAutorised nvarchar(50),
	@TrailerTypeAutorised nvarchar(50),
	@old_InterModal bit,
	@InterModal bit,
	@old_Invoiced bit,
	@Invoiced bit,
	@old_UserCreation nvarchar(50),
	@UserCreation nvarchar(50),
	@old_UserUpdate nvarchar(50),
	@UserUpdate nvarchar(50),
	@old_UserOwner nvarchar(50),
	@UserOwner nvarchar(50),
	@old_Actif bit,
	@Actif bit,
	@old_Xroute bit,
	@Xroute bit,
	@old_TripType2 nvarchar(10),
	@TripType2 nvarchar(10),
	@old_BaseFreightRate float,
	@BaseFreightRate float,
	@old_FuelSurcharge float,
	@FuelSurcharge float,
	@old_StopOver1 nvarchar(20),
	@StopOver1 nvarchar(20),
	@old_StopOver2 nvarchar(20),
	@StopOver2 nvarchar(20),
	@old_FuelSurchargeRate float,
	@FuelSurchargeRate float,
	@old_AdhocRate float,
	@AdhocRate float,
	@old_demurrage float,
	@demurrage float,
	@old_DemurageCode nvarchar(20),
	@DemurageCode nvarchar(20),
	@old_InvoiceNumber int,
	@InvoiceNumber int,
	@old_InvoiceDate datetime,
	@InvoiceDate datetime,
	@old_InvoicePath nvarchar(50),
	@InvoicePath nvarchar(50),
	@old_Line nvarchar(255),
	@Line nvarchar(255),
	@old_InvoiceEDI nvarchar(50),
	@InvoiceEDI nvarchar(50),
	@old_ShipperAccount nvarchar(255),
	@ShipperAccount nvarchar(255),
	@old_ReroutingSurcharge float,
	@ReroutingSurcharge float,
	@old_Wharehousing float,
	@Wharehousing float,
	@old_Redelivery float,
	@Redelivery float,
	@old_Cancellation float,
	@Cancellation float,
	@old_BillingAccount nvarchar(30),
	@BillingAccount nvarchar(30),
	@old_AdHocSurcharge float,
	@AdHocSurcharge float,
	@old_DriverDententionAtUnloading float,
	@DriverDententionAtUnloading float,
	@old_eShipCo smallint,
	@eShipCo smallint,
	@old_Corridor nvarchar(50),
	@Corridor nvarchar(50),
	@old_CoS bit,
	@CoS bit,
	@old_CustomClearance money,
	@CustomClearance money,
	@old_P44ToUpload bit,
	@P44ToUpload bit,
	@old_P44Uploaded bit,
	@P44Uploaded bit,
	@old_P44ShipmentID double precision,
	@P44ShipmentID double precision,
	@old_P44LastUpdate datetime,
	@P44LastUpdate datetime,
	@old_P44StatusCode nvarchar(255),
	@P44StatusCode nvarchar(255),
	@old_P44ReasonCode nvarchar(255),
	@P44ReasonCode nvarchar(255),
	@old_P44ReasonDescription nvarchar(255),
	@P44ReasonDescription nvarchar(255),
	@old_P44TrackTrailer bit,
	@P44TrackTrailer bit,
	@old_P44TrackingStarted bit,
	@P44TrackingStarted bit,
	@old_P44TrackingCompleted bit,
	@P44TrackingCompleted bit,
	@old_P44TrackingError bit,
	@P44TrackingError bit,
	@old_P44UploadError bit,
	@P44UploadError bit,
	@old_P44Latitude float,
	@P44Latitude float,
	@old_P44Longitude float,
	@P44Longitude float,
	@old_P44CurrentStop int,
	@P44CurrentStop int
AS
	UPDATE [NewCO] SET
		[NewCO]=@NewCO,
		[DateCreation]=@DateCreation,
		[DateUpdate]=@DateUpdate,
		[IdContractHolder]=@IdContractHolder,
		[ContractHolderReference]=@ContractHolderReference,
		[CMR]=@CMR,
		[SalesPrice]=@SalesPrice,
		[ConversionRate]=@ConversionRate,
		[SalesPriceCurrency]=@SalesPriceCurrency,
		[SalesPriceInCurrency]=@SalesPriceInCurrency,
		[SalesPriceVATCode]=@SalesPriceVATCode,
		[SalesPriceVATRate]=@SalesPriceVATRate,
		[SalesPriceVATAmount]=@SalesPriceVATAmount,
		[ContractHolderPaymentTerm]=@ContractHolderPaymentTerm,
		[ContractHolderPaymentTermOEM]=@ContractHolderPaymentTermOEM,
		[Comment]=@Comment,
		[InvoiceInGBP]=@InvoiceInGBP,
		[AllRisksInsurance]=@AllRisksInsurance,
		[ContractHolderEmail]=@ContractHolderEmail,
		[ContractHolderTel]=@ContractHolderTel,
		[ContractHolderMob]=@ContractHolderMob,
		[TrailerNumber]=@TrailerNumber,
		[TrailerTypeAutorised]=@TrailerTypeAutorised,
		[InterModal]=@InterModal,
		[Invoiced]=@Invoiced,
		[UserCreation]=@UserCreation,
		[UserUpdate]=@UserUpdate,
		[UserOwner]=@UserOwner,
		[Actif]=@Actif,
		[Xroute]=@Xroute,
		[TripType2]=@TripType2,
		[BaseFreightRate]=@BaseFreightRate,
		[FuelSurcharge]=@FuelSurcharge,
		[StopOver1]=@StopOver1,
		[StopOver2]=@StopOver2,
		[FuelSurchargeRate]=@FuelSurchargeRate,
		[AdhocRate]=@AdhocRate,
		[demurrage]=@demurrage,
		[DemurageCode]=@DemurageCode,
		[InvoiceNumber]=@InvoiceNumber,
		[InvoiceDate]=@InvoiceDate,
		[InvoicePath]=@InvoicePath,
		[Line]=@Line,
		[InvoiceEDI]=@InvoiceEDI,
		[ShipperAccount]=@ShipperAccount,
		[ReroutingSurcharge]=@ReroutingSurcharge,
		[Wharehousing]=@Wharehousing,
		[Redelivery]=@Redelivery,
		[Cancellation]=@Cancellation,
		[BillingAccount]=@BillingAccount,
		[AdHocSurcharge]=@AdHocSurcharge,
		[DriverDententionAtUnloading]=@DriverDententionAtUnloading,
		[eShipCo]=@eShipCo,
		[Corridor]=@Corridor,
		[CoS]=@CoS,
		[CustomClearance]=@CustomClearance,
		[P44ToUpload]=@P44ToUpload,
		[P44Uploaded]=@P44Uploaded,
		[P44ShipmentID]=@P44ShipmentID,
		[P44LastUpdate]=@P44LastUpdate,
		[P44StatusCode]=@P44StatusCode,
		[P44ReasonCode]=@P44ReasonCode,
		[P44ReasonDescription]=@P44ReasonDescription,
		[P44TrackTrailer]=@P44TrackTrailer,
		[P44TrackingStarted]=@P44TrackingStarted,
		[P44TrackingCompleted]=@P44TrackingCompleted,
		[P44TrackingError]=@P44TrackingError,
		[P44UploadError]=@P44UploadError,
		[P44Latitude]=@P44Latitude,
		[P44Longitude]=@P44Longitude,
		[P44CurrentStop]=@P44CurrentStop
	WHERE
		[IdCO] = @IdCO
GO
CREATE PROCEDURE [sp_NewCO_xpoView_delete]
	@IdCO int,
	@old_NewCO nvarchar(50),
	@old_DateCreation datetime,
	@old_DateUpdate datetime,
	@old_IdContractHolder nvarchar(6),
	@old_ContractHolderReference nvarchar(50),
	@old_CMR bit,
	@old_SalesPrice float,
	@old_ConversionRate float,
	@old_SalesPriceCurrency nvarchar(1),
	@old_SalesPriceInCurrency float,
	@old_SalesPriceVATCode nvarchar(3),
	@old_SalesPriceVATRate float,
	@old_SalesPriceVATAmount float,
	@old_ContractHolderPaymentTerm nvarchar(50),
	@old_ContractHolderPaymentTermOEM bit,
	@old_Comment nvarchar(255),
	@old_InvoiceInGBP float,
	@old_AllRisksInsurance nvarchar(3),
	@old_ContractHolderEmail nvarchar(50),
	@old_ContractHolderTel nvarchar(25),
	@old_ContractHolderMob nvarchar(25),
	@old_TrailerNumber nvarchar(30),
	@old_TrailerTypeAutorised nvarchar(50),
	@old_InterModal bit,
	@old_Invoiced bit,
	@old_UserCreation nvarchar(50),
	@old_UserUpdate nvarchar(50),
	@old_UserOwner nvarchar(50),
	@old_Actif bit,
	@old_Xroute bit,
	@old_TripType2 nvarchar(10),
	@old_BaseFreightRate float,
	@old_FuelSurcharge float,
	@old_StopOver1 nvarchar(20),
	@old_StopOver2 nvarchar(20),
	@old_FuelSurchargeRate float,
	@old_AdhocRate float,
	@old_demurrage float,
	@old_DemurageCode nvarchar(20),
	@old_InvoiceNumber int,
	@old_InvoiceDate datetime,
	@old_InvoicePath nvarchar(50),
	@old_Line nvarchar(255),
	@old_InvoiceEDI nvarchar(50),
	@old_ShipperAccount nvarchar(255),
	@old_ReroutingSurcharge float,
	@old_Wharehousing float,
	@old_Redelivery float,
	@old_Cancellation float,
	@old_BillingAccount nvarchar(30),
	@old_AdHocSurcharge float,
	@old_DriverDententionAtUnloading float,
	@old_eShipCo smallint,
	@old_Corridor nvarchar(50),
	@old_CoS bit,
	@old_CustomClearance money,
	@old_P44ToUpload bit,
	@old_P44Uploaded bit,
	@old_P44ShipmentID double precision,
	@old_P44LastUpdate datetime,
	@old_P44StatusCode nvarchar(255),
	@old_P44ReasonCode nvarchar(255),
	@old_P44ReasonDescription nvarchar(255),
	@old_P44TrackTrailer bit,
	@old_P44TrackingStarted bit,
	@old_P44TrackingCompleted bit,
	@old_P44TrackingError bit,
	@old_P44UploadError bit,
	@old_P44Latitude float,
	@old_P44Longitude float,
	@old_P44CurrentStop int
AS
	DELETE FROM [NewCO] WHERE
		[IdCO] = @IdCO
GO
CREATE TRIGGER [t_NewCO_xpoView_insert]
ON [NewCO_xpoView]
INSTEAD OF INSERT AS
BEGIN
	RAISERROR('Use sp_NewCO_xpoView_insert instead', 16, 1, null);
END
GO
CREATE TRIGGER [t_NewCO_xpoView_update]
ON [NewCO_xpoView]
INSTEAD OF UPDATE AS
BEGIN
	DECLARE @cur CURSOR
	SET @cur = CURSOR FOR
		SELECT
			i.[XpoIdentityColumn],
			d.[NewCO] as [old_NewCO],
			i.[NewCO],
			d.[DateCreation] as [old_DateCreation],
			i.[DateCreation],
			d.[DateUpdate] as [old_DateUpdate],
			i.[DateUpdate],
			d.[IdContractHolder] as [old_IdContractHolder],
			i.[IdContractHolder],
			d.[ContractHolderReference] as [old_ContractHolderReference],
			i.[ContractHolderReference],
			d.[CMR] as [old_CMR],
			i.[CMR],
			d.[SalesPrice] as [old_SalesPrice],
			i.[SalesPrice],
			d.[ConversionRate] as [old_ConversionRate],
			i.[ConversionRate],
			d.[SalesPriceCurrency] as [old_SalesPriceCurrency],
			i.[SalesPriceCurrency],
			d.[SalesPriceInCurrency] as [old_SalesPriceInCurrency],
			i.[SalesPriceInCurrency],
			d.[SalesPriceVATCode] as [old_SalesPriceVATCode],
			i.[SalesPriceVATCode],
			d.[SalesPriceVATRate] as [old_SalesPriceVATRate],
			i.[SalesPriceVATRate],
			d.[SalesPriceVATAmount] as [old_SalesPriceVATAmount],
			i.[SalesPriceVATAmount],
			d.[ContractHolderPaymentTerm] as [old_ContractHolderPaymentTerm],
			i.[ContractHolderPaymentTerm],
			d.[ContractHolderPaymentTermOEM] as [old_ContractHolderPaymentTermOEM],
			i.[ContractHolderPaymentTermOEM],
			d.[Comment] as [old_Comment],
			i.[Comment],
			d.[InvoiceInGBP] as [old_InvoiceInGBP],
			i.[InvoiceInGBP],
			d.[AllRisksInsurance] as [old_AllRisksInsurance],
			i.[AllRisksInsurance],
			d.[ContractHolderEmail] as [old_ContractHolderEmail],
			i.[ContractHolderEmail],
			d.[ContractHolderTel] as [old_ContractHolderTel],
			i.[ContractHolderTel],
			d.[ContractHolderMob] as [old_ContractHolderMob],
			i.[ContractHolderMob],
			d.[TrailerNumber] as [old_TrailerNumber],
			i.[TrailerNumber],
			d.[TrailerTypeAutorised] as [old_TrailerTypeAutorised],
			i.[TrailerTypeAutorised],
			d.[InterModal] as [old_InterModal],
			i.[InterModal],
			d.[Invoiced] as [old_Invoiced],
			i.[Invoiced],
			d.[UserCreation] as [old_UserCreation],
			i.[UserCreation],
			d.[UserUpdate] as [old_UserUpdate],
			i.[UserUpdate],
			d.[UserOwner] as [old_UserOwner],
			i.[UserOwner],
			d.[Actif] as [old_Actif],
			i.[Actif],
			d.[Xroute] as [old_Xroute],
			i.[Xroute],
			d.[TripType2] as [old_TripType2],
			i.[TripType2],
			d.[BaseFreightRate] as [old_BaseFreightRate],
			i.[BaseFreightRate],
			d.[FuelSurcharge] as [old_FuelSurcharge],
			i.[FuelSurcharge],
			d.[StopOver1] as [old_StopOver1],
			i.[StopOver1],
			d.[StopOver2] as [old_StopOver2],
			i.[StopOver2],
			d.[FuelSurchargeRate] as [old_FuelSurchargeRate],
			i.[FuelSurchargeRate],
			d.[AdhocRate] as [old_AdhocRate],
			i.[AdhocRate],
			d.[demurrage] as [old_demurrage],
			i.[demurrage],
			d.[DemurageCode] as [old_DemurageCode],
			i.[DemurageCode],
			d.[InvoiceNumber] as [old_InvoiceNumber],
			i.[InvoiceNumber],
			d.[InvoiceDate] as [old_InvoiceDate],
			i.[InvoiceDate],
			d.[InvoicePath] as [old_InvoicePath],
			i.[InvoicePath],
			d.[Line] as [old_Line],
			i.[Line],
			d.[InvoiceEDI] as [old_InvoiceEDI],
			i.[InvoiceEDI],
			d.[ShipperAccount] as [old_ShipperAccount],
			i.[ShipperAccount],
			d.[ReroutingSurcharge] as [old_ReroutingSurcharge],
			i.[ReroutingSurcharge],
			d.[Wharehousing] as [old_Wharehousing],
			i.[Wharehousing],
			d.[Redelivery] as [old_Redelivery],
			i.[Redelivery],
			d.[Cancellation] as [old_Cancellation],
			i.[Cancellation],
			d.[BillingAccount] as [old_BillingAccount],
			i.[BillingAccount],
			d.[AdHocSurcharge] as [old_AdHocSurcharge],
			i.[AdHocSurcharge],
			d.[DriverDententionAtUnloading] as [old_DriverDententionAtUnloading],
			i.[DriverDententionAtUnloading],
			d.[eShipCo] as [old_eShipCo],
			i.[eShipCo],
			d.[Corridor] as [old_Corridor],
			i.[Corridor],
			d.[CoS] as [old_CoS],
			i.[CoS],
			d.[CustomClearance] as [old_CustomClearance],
			i.[CustomClearance],
			d.[P44ToUpload] as [old_P44ToUpload],
			i.[P44ToUpload],
			d.[P44Uploaded] as [old_P44Uploaded],
			i.[P44Uploaded],
			d.[P44ShipmentID] as [old_P44ShipmentID],
			i.[P44ShipmentID],
			d.[P44LastUpdate] as [old_P44LastUpdate],
			i.[P44LastUpdate],
			d.[P44StatusCode] as [old_P44StatusCode],
			i.[P44StatusCode],
			d.[P44ReasonCode] as [old_P44ReasonCode],
			i.[P44ReasonCode],
			d.[P44ReasonDescription] as [old_P44ReasonDescription],
			i.[P44ReasonDescription],
			d.[P44TrackTrailer] as [old_P44TrackTrailer],
			i.[P44TrackTrailer],
			d.[P44TrackingStarted] as [old_P44TrackingStarted],
			i.[P44TrackingStarted],
			d.[P44TrackingCompleted] as [old_P44TrackingCompleted],
			i.[P44TrackingCompleted],
			d.[P44TrackingError] as [old_P44TrackingError],
			i.[P44TrackingError],
			d.[P44UploadError] as [old_P44UploadError],
			i.[P44UploadError],
			d.[P44Latitude] as [old_P44Latitude],
			i.[P44Latitude],
			d.[P44Longitude] as [old_P44Longitude],
			i.[P44Longitude],
			d.[P44CurrentStop] as [old_P44CurrentStop],
			i.[P44CurrentStop]
		FROM
			inserted i
			INNER JOIN
			deleted d
			ON
				i.[XpoIdentityColumn] = d.[XpoIdentityColumn]
	OPEN @cur
	DECLARE @XpoIdentityColumn int
	DECLARE @old_NewCO nvarchar(50)
	DECLARE @NewCO nvarchar(50)
	DECLARE @old_DateCreation datetime
	DECLARE @DateCreation datetime
	DECLARE @old_DateUpdate datetime
	DECLARE @DateUpdate datetime
	DECLARE @old_IdContractHolder nvarchar(6)
	DECLARE @IdContractHolder nvarchar(6)
	DECLARE @old_ContractHolderReference nvarchar(50)
	DECLARE @ContractHolderReference nvarchar(50)
	DECLARE @old_CMR bit
	DECLARE @CMR bit
	DECLARE @old_SalesPrice float
	DECLARE @SalesPrice float
	DECLARE @old_ConversionRate float
	DECLARE @ConversionRate float
	DECLARE @old_SalesPriceCurrency nvarchar(1)
	DECLARE @SalesPriceCurrency nvarchar(1)
	DECLARE @old_SalesPriceInCurrency float
	DECLARE @SalesPriceInCurrency float
	DECLARE @old_SalesPriceVATCode nvarchar(3)
	DECLARE @SalesPriceVATCode nvarchar(3)
	DECLARE @old_SalesPriceVATRate float
	DECLARE @SalesPriceVATRate float
	DECLARE @old_SalesPriceVATAmount float
	DECLARE @SalesPriceVATAmount float
	DECLARE @old_ContractHolderPaymentTerm nvarchar(50)
	DECLARE @ContractHolderPaymentTerm nvarchar(50)
	DECLARE @old_ContractHolderPaymentTermOEM bit
	DECLARE @ContractHolderPaymentTermOEM bit
	DECLARE @old_Comment nvarchar(255)
	DECLARE @Comment nvarchar(255)
	DECLARE @old_InvoiceInGBP float
	DECLARE @InvoiceInGBP float
	DECLARE @old_AllRisksInsurance nvarchar(3)
	DECLARE @AllRisksInsurance nvarchar(3)
	DECLARE @old_ContractHolderEmail nvarchar(50)
	DECLARE @ContractHolderEmail nvarchar(50)
	DECLARE @old_ContractHolderTel nvarchar(25)
	DECLARE @ContractHolderTel nvarchar(25)
	DECLARE @old_ContractHolderMob nvarchar(25)
	DECLARE @ContractHolderMob nvarchar(25)
	DECLARE @old_TrailerNumber nvarchar(30)
	DECLARE @TrailerNumber nvarchar(30)
	DECLARE @old_TrailerTypeAutorised nvarchar(50)
	DECLARE @TrailerTypeAutorised nvarchar(50)
	DECLARE @old_InterModal bit
	DECLARE @InterModal bit
	DECLARE @old_Invoiced bit
	DECLARE @Invoiced bit
	DECLARE @old_UserCreation nvarchar(50)
	DECLARE @UserCreation nvarchar(50)
	DECLARE @old_UserUpdate nvarchar(50)
	DECLARE @UserUpdate nvarchar(50)
	DECLARE @old_UserOwner nvarchar(50)
	DECLARE @UserOwner nvarchar(50)
	DECLARE @old_Actif bit
	DECLARE @Actif bit
	DECLARE @old_Xroute bit
	DECLARE @Xroute bit
	DECLARE @old_TripType2 nvarchar(10)
	DECLARE @TripType2 nvarchar(10)
	DECLARE @old_BaseFreightRate float
	DECLARE @BaseFreightRate float
	DECLARE @old_FuelSurcharge float
	DECLARE @FuelSurcharge float
	DECLARE @old_StopOver1 nvarchar(20)
	DECLARE @StopOver1 nvarchar(20)
	DECLARE @old_StopOver2 nvarchar(20)
	DECLARE @StopOver2 nvarchar(20)
	DECLARE @old_FuelSurchargeRate float
	DECLARE @FuelSurchargeRate float
	DECLARE @old_AdhocRate float
	DECLARE @AdhocRate float
	DECLARE @old_demurrage float
	DECLARE @demurrage float
	DECLARE @old_DemurageCode nvarchar(20)
	DECLARE @DemurageCode nvarchar(20)
	DECLARE @old_InvoiceNumber int
	DECLARE @InvoiceNumber int
	DECLARE @old_InvoiceDate datetime
	DECLARE @InvoiceDate datetime
	DECLARE @old_InvoicePath nvarchar(50)
	DECLARE @InvoicePath nvarchar(50)
	DECLARE @old_Line nvarchar(255)
	DECLARE @Line nvarchar(255)
	DECLARE @old_InvoiceEDI nvarchar(50)
	DECLARE @InvoiceEDI nvarchar(50)
	DECLARE @old_ShipperAccount nvarchar(255)
	DECLARE @ShipperAccount nvarchar(255)
	DECLARE @old_ReroutingSurcharge float
	DECLARE @ReroutingSurcharge float
	DECLARE @old_Wharehousing float
	DECLARE @Wharehousing float
	DECLARE @old_Redelivery float
	DECLARE @Redelivery float
	DECLARE @old_Cancellation float
	DECLARE @Cancellation float
	DECLARE @old_BillingAccount nvarchar(30)
	DECLARE @BillingAccount nvarchar(30)
	DECLARE @old_AdHocSurcharge float
	DECLARE @AdHocSurcharge float
	DECLARE @old_DriverDententionAtUnloading float
	DECLARE @DriverDententionAtUnloading float
	DECLARE @old_eShipCo smallint
	DECLARE @eShipCo smallint
	DECLARE @old_Corridor nvarchar(50)
	DECLARE @Corridor nvarchar(50)
	DECLARE @old_CoS bit
	DECLARE @CoS bit
	DECLARE @old_CustomClearance money
	DECLARE @CustomClearance money
	DECLARE @old_P44ToUpload bit
	DECLARE @P44ToUpload bit
	DECLARE @old_P44Uploaded bit
	DECLARE @P44Uploaded bit
	DECLARE @old_P44ShipmentID double precision
	DECLARE @P44ShipmentID double precision
	DECLARE @old_P44LastUpdate datetime
	DECLARE @P44LastUpdate datetime
	DECLARE @old_P44StatusCode nvarchar(255)
	DECLARE @P44StatusCode nvarchar(255)
	DECLARE @old_P44ReasonCode nvarchar(255)
	DECLARE @P44ReasonCode nvarchar(255)
	DECLARE @old_P44ReasonDescription nvarchar(255)
	DECLARE @P44ReasonDescription nvarchar(255)
	DECLARE @old_P44TrackTrailer bit
	DECLARE @P44TrackTrailer bit
	DECLARE @old_P44TrackingStarted bit
	DECLARE @P44TrackingStarted bit
	DECLARE @old_P44TrackingCompleted bit
	DECLARE @P44TrackingCompleted bit
	DECLARE @old_P44TrackingError bit
	DECLARE @P44TrackingError bit
	DECLARE @old_P44UploadError bit
	DECLARE @P44UploadError bit
	DECLARE @old_P44Latitude float
	DECLARE @P44Latitude float
	DECLARE @old_P44Longitude float
	DECLARE @P44Longitude float
	DECLARE @old_P44CurrentStop int
	DECLARE @P44CurrentStop int
	FETCH NEXT FROM @cur INTO
		@XpoIdentityColumn,
		@old_NewCO,
		@NewCO,
		@old_DateCreation,
		@DateCreation,
		@old_DateUpdate,
		@DateUpdate,
		@old_IdContractHolder,
		@IdContractHolder,
		@old_ContractHolderReference,
		@ContractHolderReference,
		@old_CMR,
		@CMR,
		@old_SalesPrice,
		@SalesPrice,
		@old_ConversionRate,
		@ConversionRate,
		@old_SalesPriceCurrency,
		@SalesPriceCurrency,
		@old_SalesPriceInCurrency,
		@SalesPriceInCurrency,
		@old_SalesPriceVATCode,
		@SalesPriceVATCode,
		@old_SalesPriceVATRate,
		@SalesPriceVATRate,
		@old_SalesPriceVATAmount,
		@SalesPriceVATAmount,
		@old_ContractHolderPaymentTerm,
		@ContractHolderPaymentTerm,
		@old_ContractHolderPaymentTermOEM,
		@ContractHolderPaymentTermOEM,
		@old_Comment,
		@Comment,
		@old_InvoiceInGBP,
		@InvoiceInGBP,
		@old_AllRisksInsurance,
		@AllRisksInsurance,
		@old_ContractHolderEmail,
		@ContractHolderEmail,
		@old_ContractHolderTel,
		@ContractHolderTel,
		@old_ContractHolderMob,
		@ContractHolderMob,
		@old_TrailerNumber,
		@TrailerNumber,
		@old_TrailerTypeAutorised,
		@TrailerTypeAutorised,
		@old_InterModal,
		@InterModal,
		@old_Invoiced,
		@Invoiced,
		@old_UserCreation,
		@UserCreation,
		@old_UserUpdate,
		@UserUpdate,
		@old_UserOwner,
		@UserOwner,
		@old_Actif,
		@Actif,
		@old_Xroute,
		@Xroute,
		@old_TripType2,
		@TripType2,
		@old_BaseFreightRate,
		@BaseFreightRate,
		@old_FuelSurcharge,
		@FuelSurcharge,
		@old_StopOver1,
		@StopOver1,
		@old_StopOver2,
		@StopOver2,
		@old_FuelSurchargeRate,
		@FuelSurchargeRate,
		@old_AdhocRate,
		@AdhocRate,
		@old_demurrage,
		@demurrage,
		@old_DemurageCode,
		@DemurageCode,
		@old_InvoiceNumber,
		@InvoiceNumber,
		@old_InvoiceDate,
		@InvoiceDate,
		@old_InvoicePath,
		@InvoicePath,
		@old_Line,
		@Line,
		@old_InvoiceEDI,
		@InvoiceEDI,
		@old_ShipperAccount,
		@ShipperAccount,
		@old_ReroutingSurcharge,
		@ReroutingSurcharge,
		@old_Wharehousing,
		@Wharehousing,
		@old_Redelivery,
		@Redelivery,
		@old_Cancellation,
		@Cancellation,
		@old_BillingAccount,
		@BillingAccount,
		@old_AdHocSurcharge,
		@AdHocSurcharge,
		@old_DriverDententionAtUnloading,
		@DriverDententionAtUnloading,
		@old_eShipCo,
		@eShipCo,
		@old_Corridor,
		@Corridor,
		@old_CoS,
		@CoS,
		@old_CustomClearance,
		@CustomClearance,
		@old_P44ToUpload,
		@P44ToUpload,
		@old_P44Uploaded,
		@P44Uploaded,
		@old_P44ShipmentID,
		@P44ShipmentID,
		@old_P44LastUpdate,
		@P44LastUpdate,
		@old_P44StatusCode,
		@P44StatusCode,
		@old_P44ReasonCode,
		@P44ReasonCode,
		@old_P44ReasonDescription,
		@P44ReasonDescription,
		@old_P44TrackTrailer,
		@P44TrackTrailer,
		@old_P44TrackingStarted,
		@P44TrackingStarted,
		@old_P44TrackingCompleted,
		@P44TrackingCompleted,
		@old_P44TrackingError,
		@P44TrackingError,
		@old_P44UploadError,
		@P44UploadError,
		@old_P44Latitude,
		@P44Latitude,
		@old_P44Longitude,
		@P44Longitude,
		@old_P44CurrentStop,
		@P44CurrentStop
	WHILE(@@fetch_status <> -1)
	BEGIN
		EXEC [sp_NewCO_xpoView_update]
			@XpoIdentityColumn,
			@old_NewCO,
			@NewCO,
			@old_DateCreation,
			@DateCreation,
			@old_DateUpdate,
			@DateUpdate,
			@old_IdContractHolder,
			@IdContractHolder,
			@old_ContractHolderReference,
			@ContractHolderReference,
			@old_CMR,
			@CMR,
			@old_SalesPrice,
			@SalesPrice,
			@old_ConversionRate,
			@ConversionRate,
			@old_SalesPriceCurrency,
			@SalesPriceCurrency,
			@old_SalesPriceInCurrency,
			@SalesPriceInCurrency,
			@old_SalesPriceVATCode,
			@SalesPriceVATCode,
			@old_SalesPriceVATRate,
			@SalesPriceVATRate,
			@old_SalesPriceVATAmount,
			@SalesPriceVATAmount,
			@old_ContractHolderPaymentTerm,
			@ContractHolderPaymentTerm,
			@old_ContractHolderPaymentTermOEM,
			@ContractHolderPaymentTermOEM,
			@old_Comment,
			@Comment,
			@old_InvoiceInGBP,
			@InvoiceInGBP,
			@old_AllRisksInsurance,
			@AllRisksInsurance,
			@old_ContractHolderEmail,
			@ContractHolderEmail,
			@old_ContractHolderTel,
			@ContractHolderTel,
			@old_ContractHolderMob,
			@ContractHolderMob,
			@old_TrailerNumber,
			@TrailerNumber,
			@old_TrailerTypeAutorised,
			@TrailerTypeAutorised,
			@old_InterModal,
			@InterModal,
			@old_Invoiced,
			@Invoiced,
			@old_UserCreation,
			@UserCreation,
			@old_UserUpdate,
			@UserUpdate,
			@old_UserOwner,
			@UserOwner,
			@old_Actif,
			@Actif,
			@old_Xroute,
			@Xroute,
			@old_TripType2,
			@TripType2,
			@old_BaseFreightRate,
			@BaseFreightRate,
			@old_FuelSurcharge,
			@FuelSurcharge,
			@old_StopOver1,
			@StopOver1,
			@old_StopOver2,
			@StopOver2,
			@old_FuelSurchargeRate,
			@FuelSurchargeRate,
			@old_AdhocRate,
			@AdhocRate,
			@old_demurrage,
			@demurrage,
			@old_DemurageCode,
			@DemurageCode,
			@old_InvoiceNumber,
			@InvoiceNumber,
			@old_InvoiceDate,
			@InvoiceDate,
			@old_InvoicePath,
			@InvoicePath,
			@old_Line,
			@Line,
			@old_InvoiceEDI,
			@InvoiceEDI,
			@old_ShipperAccount,
			@ShipperAccount,
			@old_ReroutingSurcharge,
			@ReroutingSurcharge,
			@old_Wharehousing,
			@Wharehousing,
			@old_Redelivery,
			@Redelivery,
			@old_Cancellation,
			@Cancellation,
			@old_BillingAccount,
			@BillingAccount,
			@old_AdHocSurcharge,
			@AdHocSurcharge,
			@old_DriverDententionAtUnloading,
			@DriverDententionAtUnloading,
			@old_eShipCo,
			@eShipCo,
			@old_Corridor,
			@Corridor,
			@old_CoS,
			@CoS,
			@old_CustomClearance,
			@CustomClearance,
			@old_P44ToUpload,
			@P44ToUpload,
			@old_P44Uploaded,
			@P44Uploaded,
			@old_P44ShipmentID,
			@P44ShipmentID,
			@old_P44LastUpdate,
			@P44LastUpdate,
			@old_P44StatusCode,
			@P44StatusCode,
			@old_P44ReasonCode,
			@P44ReasonCode,
			@old_P44ReasonDescription,
			@P44ReasonDescription,
			@old_P44TrackTrailer,
			@P44TrackTrailer,
			@old_P44TrackingStarted,
			@P44TrackingStarted,
			@old_P44TrackingCompleted,
			@P44TrackingCompleted,
			@old_P44TrackingError,
			@P44TrackingError,
			@old_P44UploadError,
			@P44UploadError,
			@old_P44Latitude,
			@P44Latitude,
			@old_P44Longitude,
			@P44Longitude,
			@old_P44CurrentStop,
			@P44CurrentStop
		FETCH NEXT FROM @cur INTO
			@XpoIdentityColumn,
			@old_NewCO,
			@NewCO,
			@old_DateCreation,
			@DateCreation,
			@old_DateUpdate,
			@DateUpdate,
			@old_IdContractHolder,
			@IdContractHolder,
			@old_ContractHolderReference,
			@ContractHolderReference,
			@old_CMR,
			@CMR,
			@old_SalesPrice,
			@SalesPrice,
			@old_ConversionRate,
			@ConversionRate,
			@old_SalesPriceCurrency,
			@SalesPriceCurrency,
			@old_SalesPriceInCurrency,
			@SalesPriceInCurrency,
			@old_SalesPriceVATCode,
			@SalesPriceVATCode,
			@old_SalesPriceVATRate,
			@SalesPriceVATRate,
			@old_SalesPriceVATAmount,
			@SalesPriceVATAmount,
			@old_ContractHolderPaymentTerm,
			@ContractHolderPaymentTerm,
			@old_ContractHolderPaymentTermOEM,
			@ContractHolderPaymentTermOEM,
			@old_Comment,
			@Comment,
			@old_InvoiceInGBP,
			@InvoiceInGBP,
			@old_AllRisksInsurance,
			@AllRisksInsurance,
			@old_ContractHolderEmail,
			@ContractHolderEmail,
			@old_ContractHolderTel,
			@ContractHolderTel,
			@old_ContractHolderMob,
			@ContractHolderMob,
			@old_TrailerNumber,
			@TrailerNumber,
			@old_TrailerTypeAutorised,
			@TrailerTypeAutorised,
			@old_InterModal,
			@InterModal,
			@old_Invoiced,
			@Invoiced,
			@old_UserCreation,
			@UserCreation,
			@old_UserUpdate,
			@UserUpdate,
			@old_UserOwner,
			@UserOwner,
			@old_Actif,
			@Actif,
			@old_Xroute,
			@Xroute,
			@old_TripType2,
			@TripType2,
			@old_BaseFreightRate,
			@BaseFreightRate,
			@old_FuelSurcharge,
			@FuelSurcharge,
			@old_StopOver1,
			@StopOver1,
			@old_StopOver2,
			@StopOver2,
			@old_FuelSurchargeRate,
			@FuelSurchargeRate,
			@old_AdhocRate,
			@AdhocRate,
			@old_demurrage,
			@demurrage,
			@old_DemurageCode,
			@DemurageCode,
			@old_InvoiceNumber,
			@InvoiceNumber,
			@old_InvoiceDate,
			@InvoiceDate,
			@old_InvoicePath,
			@InvoicePath,
			@old_Line,
			@Line,
			@old_InvoiceEDI,
			@InvoiceEDI,
			@old_ShipperAccount,
			@ShipperAccount,
			@old_ReroutingSurcharge,
			@ReroutingSurcharge,
			@old_Wharehousing,
			@Wharehousing,
			@old_Redelivery,
			@Redelivery,
			@old_Cancellation,
			@Cancellation,
			@old_BillingAccount,
			@BillingAccount,
			@old_AdHocSurcharge,
			@AdHocSurcharge,
			@old_DriverDententionAtUnloading,
			@DriverDententionAtUnloading,
			@old_eShipCo,
			@eShipCo,
			@old_Corridor,
			@Corridor,
			@old_CoS,
			@CoS,
			@old_CustomClearance,
			@CustomClearance,
			@old_P44ToUpload,
			@P44ToUpload,
			@old_P44Uploaded,
			@P44Uploaded,
			@old_P44ShipmentID,
			@P44ShipmentID,
			@old_P44LastUpdate,
			@P44LastUpdate,
			@old_P44StatusCode,
			@P44StatusCode,
			@old_P44ReasonCode,
			@P44ReasonCode,
			@old_P44ReasonDescription,
			@P44ReasonDescription,
			@old_P44TrackTrailer,
			@P44TrackTrailer,
			@old_P44TrackingStarted,
			@P44TrackingStarted,
			@old_P44TrackingCompleted,
			@P44TrackingCompleted,
			@old_P44TrackingError,
			@P44TrackingError,
			@old_P44UploadError,
			@P44UploadError,
			@old_P44Latitude,
			@P44Latitude,
			@old_P44Longitude,
			@P44Longitude,
			@old_P44CurrentStop,
			@P44CurrentStop
	END
	CLOSE @cur
	DEALLOCATE @cur
END
GO
CREATE TRIGGER [t_NewCO_xpoView_delete]
ON [NewCO_xpoView]
INSTEAD OF DELETE AS
BEGIN
	DECLARE @cur CURSOR
	SET @cur = CURSOR FOR
		SELECT
			[XpoIdentityColumn],
			[NewCO],
			[DateCreation],
			[DateUpdate],
			[IdContractHolder],
			[ContractHolderReference],
			[CMR],
			[SalesPrice],
			[ConversionRate],
			[SalesPriceCurrency],
			[SalesPriceInCurrency],
			[SalesPriceVATCode],
			[SalesPriceVATRate],
			[SalesPriceVATAmount],
			[ContractHolderPaymentTerm],
			[ContractHolderPaymentTermOEM],
			[Comment],
			[InvoiceInGBP],
			[AllRisksInsurance],
			[ContractHolderEmail],
			[ContractHolderTel],
			[ContractHolderMob],
			[TrailerNumber],
			[TrailerTypeAutorised],
			[InterModal],
			[Invoiced],
			[UserCreation],
			[UserUpdate],
			[UserOwner],
			[Actif],
			[Xroute],
			[TripType2],
			[BaseFreightRate],
			[FuelSurcharge],
			[StopOver1],
			[StopOver2],
			[FuelSurchargeRate],
			[AdhocRate],
			[demurrage],
			[DemurageCode],
			[InvoiceNumber],
			[InvoiceDate],
			[InvoicePath],
			[Line],
			[InvoiceEDI],
			[ShipperAccount],
			[ReroutingSurcharge],
			[Wharehousing],
			[Redelivery],
			[Cancellation],
			[BillingAccount],
			[AdHocSurcharge],
			[DriverDententionAtUnloading],
			[eShipCo],
			[Corridor],
			[CoS],
			[CustomClearance],
			[P44ToUpload],
			[P44Uploaded],
			[P44ShipmentID],
			[P44LastUpdate],
			[P44StatusCode],
			[P44ReasonCode],
			[P44ReasonDescription],
			[P44TrackTrailer],
			[P44TrackingStarted],
			[P44TrackingCompleted],
			[P44TrackingError],
			[P44UploadError],
			[P44Latitude],
			[P44Longitude],
			[P44CurrentStop]
		FROM deleted
	OPEN @cur
	DECLARE @XpoIdentityColumn int
	DECLARE @NewCO nvarchar(50)
	DECLARE @DateCreation datetime
	DECLARE @DateUpdate datetime
	DECLARE @IdContractHolder nvarchar(6)
	DECLARE @ContractHolderReference nvarchar(50)
	DECLARE @CMR bit
	DECLARE @SalesPrice float
	DECLARE @ConversionRate float
	DECLARE @SalesPriceCurrency nvarchar(1)
	DECLARE @SalesPriceInCurrency float
	DECLARE @SalesPriceVATCode nvarchar(3)
	DECLARE @SalesPriceVATRate float
	DECLARE @SalesPriceVATAmount float
	DECLARE @ContractHolderPaymentTerm nvarchar(50)
	DECLARE @ContractHolderPaymentTermOEM bit
	DECLARE @Comment nvarchar(255)
	DECLARE @InvoiceInGBP float
	DECLARE @AllRisksInsurance nvarchar(3)
	DECLARE @ContractHolderEmail nvarchar(50)
	DECLARE @ContractHolderTel nvarchar(25)
	DECLARE @ContractHolderMob nvarchar(25)
	DECLARE @TrailerNumber nvarchar(30)
	DECLARE @TrailerTypeAutorised nvarchar(50)
	DECLARE @InterModal bit
	DECLARE @Invoiced bit
	DECLARE @UserCreation nvarchar(50)
	DECLARE @UserUpdate nvarchar(50)
	DECLARE @UserOwner nvarchar(50)
	DECLARE @Actif bit
	DECLARE @Xroute bit
	DECLARE @TripType2 nvarchar(10)
	DECLARE @BaseFreightRate float
	DECLARE @FuelSurcharge float
	DECLARE @StopOver1 nvarchar(20)
	DECLARE @StopOver2 nvarchar(20)
	DECLARE @FuelSurchargeRate float
	DECLARE @AdhocRate float
	DECLARE @demurrage float
	DECLARE @DemurageCode nvarchar(20)
	DECLARE @InvoiceNumber int
	DECLARE @InvoiceDate datetime
	DECLARE @InvoicePath nvarchar(50)
	DECLARE @Line nvarchar(255)
	DECLARE @InvoiceEDI nvarchar(50)
	DECLARE @ShipperAccount nvarchar(255)
	DECLARE @ReroutingSurcharge float
	DECLARE @Wharehousing float
	DECLARE @Redelivery float
	DECLARE @Cancellation float
	DECLARE @BillingAccount nvarchar(30)
	DECLARE @AdHocSurcharge float
	DECLARE @DriverDententionAtUnloading float
	DECLARE @eShipCo smallint
	DECLARE @Corridor nvarchar(50)
	DECLARE @CoS bit
	DECLARE @CustomClearance money
	DECLARE @P44ToUpload bit
	DECLARE @P44Uploaded bit
	DECLARE @P44ShipmentID double precision
	DECLARE @P44LastUpdate datetime
	DECLARE @P44StatusCode nvarchar(255)
	DECLARE @P44ReasonCode nvarchar(255)
	DECLARE @P44ReasonDescription nvarchar(255)
	DECLARE @P44TrackTrailer bit
	DECLARE @P44TrackingStarted bit
	DECLARE @P44TrackingCompleted bit
	DECLARE @P44TrackingError bit
	DECLARE @P44UploadError bit
	DECLARE @P44Latitude float
	DECLARE @P44Longitude float
	DECLARE @P44CurrentStop int
	FETCH NEXT FROM @cur INTO
		@XpoIdentityColumn,
		@NewCO,
		@DateCreation,
		@DateUpdate,
		@IdContractHolder,
		@ContractHolderReference,
		@CMR,
		@SalesPrice,
		@ConversionRate,
		@SalesPriceCurrency,
		@SalesPriceInCurrency,
		@SalesPriceVATCode,
		@SalesPriceVATRate,
		@SalesPriceVATAmount,
		@ContractHolderPaymentTerm,
		@ContractHolderPaymentTermOEM,
		@Comment,
		@InvoiceInGBP,
		@AllRisksInsurance,
		@ContractHolderEmail,
		@ContractHolderTel,
		@ContractHolderMob,
		@TrailerNumber,
		@TrailerTypeAutorised,
		@InterModal,
		@Invoiced,
		@UserCreation,
		@UserUpdate,
		@UserOwner,
		@Actif,
		@Xroute,
		@TripType2,
		@BaseFreightRate,
		@FuelSurcharge,
		@StopOver1,
		@StopOver2,
		@FuelSurchargeRate,
		@AdhocRate,
		@demurrage,
		@DemurageCode,
		@InvoiceNumber,
		@InvoiceDate,
		@InvoicePath,
		@Line,
		@InvoiceEDI,
		@ShipperAccount,
		@ReroutingSurcharge,
		@Wharehousing,
		@Redelivery,
		@Cancellation,
		@BillingAccount,
		@AdHocSurcharge,
		@DriverDententionAtUnloading,
		@eShipCo,
		@Corridor,
		@CoS,
		@CustomClearance,
		@P44ToUpload,
		@P44Uploaded,
		@P44ShipmentID,
		@P44LastUpdate,
		@P44StatusCode,
		@P44ReasonCode,
		@P44ReasonDescription,
		@P44TrackTrailer,
		@P44TrackingStarted,
		@P44TrackingCompleted,
		@P44TrackingError,
		@P44UploadError,
		@P44Latitude,
		@P44Longitude,
		@P44CurrentStop
	WHILE(@@fetch_status <> -1)
	BEGIN
		EXEC [sp_NewCO_xpoView_delete]
			@XpoIdentityColumn,
			@NewCO,
			@DateCreation,
			@DateUpdate,
			@IdContractHolder,
			@ContractHolderReference,
			@CMR,
			@SalesPrice,
			@ConversionRate,
			@SalesPriceCurrency,
			@SalesPriceInCurrency,
			@SalesPriceVATCode,
			@SalesPriceVATRate,
			@SalesPriceVATAmount,
			@ContractHolderPaymentTerm,
			@ContractHolderPaymentTermOEM,
			@Comment,
			@InvoiceInGBP,
			@AllRisksInsurance,
			@ContractHolderEmail,
			@ContractHolderTel,
			@ContractHolderMob,
			@TrailerNumber,
			@TrailerTypeAutorised,
			@InterModal,
			@Invoiced,
			@UserCreation,
			@UserUpdate,
			@UserOwner,
			@Actif,
			@Xroute,
			@TripType2,
			@BaseFreightRate,
			@FuelSurcharge,
			@StopOver1,
			@StopOver2,
			@FuelSurchargeRate,
			@AdhocRate,
			@demurrage,
			@DemurageCode,
			@InvoiceNumber,
			@InvoiceDate,
			@InvoicePath,
			@Line,
			@InvoiceEDI,
			@ShipperAccount,
			@ReroutingSurcharge,
			@Wharehousing,
			@Redelivery,
			@Cancellation,
			@BillingAccount,
			@AdHocSurcharge,
			@DriverDententionAtUnloading,
			@eShipCo,
			@Corridor,
			@CoS,
			@CustomClearance,
			@P44ToUpload,
			@P44Uploaded,
			@P44ShipmentID,
			@P44LastUpdate,
			@P44StatusCode,
			@P44ReasonCode,
			@P44ReasonDescription,
			@P44TrackTrailer,
			@P44TrackingStarted,
			@P44TrackingCompleted,
			@P44TrackingError,
			@P44UploadError,
			@P44Latitude,
			@P44Longitude,
			@P44CurrentStop
		FETCH NEXT FROM @cur INTO
			@XpoIdentityColumn,
			@NewCO,
			@DateCreation,
			@DateUpdate,
			@IdContractHolder,
			@ContractHolderReference,
			@CMR,
			@SalesPrice,
			@ConversionRate,
			@SalesPriceCurrency,
			@SalesPriceInCurrency,
			@SalesPriceVATCode,
			@SalesPriceVATRate,
			@SalesPriceVATAmount,
			@ContractHolderPaymentTerm,
			@ContractHolderPaymentTermOEM,
			@Comment,
			@InvoiceInGBP,
			@AllRisksInsurance,
			@ContractHolderEmail,
			@ContractHolderTel,
			@ContractHolderMob,
			@TrailerNumber,
			@TrailerTypeAutorised,
			@InterModal,
			@Invoiced,
			@UserCreation,
			@UserUpdate,
			@UserOwner,
			@Actif,
			@Xroute,
			@TripType2,
			@BaseFreightRate,
			@FuelSurcharge,
			@StopOver1,
			@StopOver2,
			@FuelSurchargeRate,
			@AdhocRate,
			@demurrage,
			@DemurageCode,
			@InvoiceNumber,
			@InvoiceDate,
			@InvoicePath,
			@Line,
			@InvoiceEDI,
			@ShipperAccount,
			@ReroutingSurcharge,
			@Wharehousing,
			@Redelivery,
			@Cancellation,
			@BillingAccount,
			@AdHocSurcharge,
			@DriverDententionAtUnloading,
			@eShipCo,
			@Corridor,
			@CoS,
			@CustomClearance,
			@P44ToUpload,
			@P44Uploaded,
			@P44ShipmentID,
			@P44LastUpdate,
			@P44StatusCode,
			@P44ReasonCode,
			@P44ReasonDescription,
			@P44TrackTrailer,
			@P44TrackingStarted,
			@P44TrackingCompleted,
			@P44TrackingError,
			@P44UploadError,
			@P44Latitude,
			@P44Longitude,
			@P44CurrentStop
	END
	CLOSE @cur
	DEALLOCATE @cur
END
GO


/*
DROP TRIGGER [t_Movement_xpoView_delete]
GO
DROP TRIGGER [t_Movement_xpoView_update]
GO
DROP TRIGGER [t_Movement_xpoView_insert]
GO
DROP PROCEDURE [sp_Movement_xpoView_delete]
GO
DROP PROCEDURE [sp_Movement_xpoView_update]
GO
DROP PROCEDURE [sp_Movement_xpoView_insert]
GO
DROP VIEW [Movement_xpoView]
GO

DROP TRIGGER [t_NewCO_xpoView_delete]
GO
DROP TRIGGER [t_NewCO_xpoView_update]
GO
DROP TRIGGER [t_NewCO_xpoView_insert]
GO
DROP PROCEDURE [sp_NewCO_xpoView_delete]
GO
DROP PROCEDURE [sp_NewCO_xpoView_update]
GO
DROP PROCEDURE [sp_NewCO_xpoView_insert]
GO
DROP VIEW [NewCO_xpoView]
GO


*/

