
namespace EFRET_TMS
{
    partial class TrailerHistory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTimeSpanColumn gridViewTimeSpanColumn1 = new Telerik.WinControls.UI.GridViewTimeSpanColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn2 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.Data.SortDescriptor sortDescriptor1 = new Telerik.WinControls.Data.SortDescriptor();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TrailerHistory));
            this.radGridView1 = new Telerik.WinControls.UI.RadGridView();
            this.bindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.axsTrailerHistory1 = new EFRET_TMS.axsTrailerHistory();
            this.trailerHistoryTableAdapter1 = new EFRET_TMS.axsTrailerHistoryTableAdapters.TrailerHistoryTableAdapter();
            this.behaviorManager1 = new DevExpress.Utils.Behaviors.BehaviorManager(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.axsTrailerHistory1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.behaviorManager1)).BeginInit();
            this.SuspendLayout();
            // 
            // radGridView1
            // 
            this.radGridView1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(248)))));
            this.radGridView1.Cursor = System.Windows.Forms.Cursors.Default;
            this.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radGridView1.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.radGridView1.ForeColor = System.Drawing.Color.Black;
            this.radGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radGridView1.Location = new System.Drawing.Point(0, 0);
            // 
            // 
            // 
            this.radGridView1.MasterTemplate.AllowAddNewRow = false;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "HistId";
            gridViewDecimalColumn1.HeaderText = "HistId";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "HistId";
            gridViewDecimalColumn1.ReadOnly = true;
            gridViewDecimalColumn1.Width = 42;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Trailer";
            gridViewTextBoxColumn1.HeaderText = "Trailer";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Trailer";
            gridViewTextBoxColumn1.Width = 97;
            gridViewDecimalColumn2.DataType = typeof(int);
            gridViewDecimalColumn2.EnableExpressionEditor = false;
            gridViewDecimalColumn2.FieldName = "IdCO";
            gridViewDecimalColumn2.HeaderText = "IdCO";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "IdCO";
            gridViewDecimalColumn2.Width = 82;
            gridViewDecimalColumn3.DataType = typeof(int);
            gridViewDecimalColumn3.EnableExpressionEditor = false;
            gridViewDecimalColumn3.FieldName = "idMovement";
            gridViewDecimalColumn3.HeaderText = "idMovement";
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "idMovement";
            gridViewDecimalColumn3.Width = 82;
            gridViewDateTimeColumn1.EnableExpressionEditor = false;
            gridViewDateTimeColumn1.FieldName = "DateTrailerHistory";
            gridViewDateTimeColumn1.HeaderText = "DateTrailerHistory";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.Name = "DateTrailerHistory";
            gridViewDateTimeColumn1.Width = 112;
            gridViewTimeSpanColumn1.EnableExpressionEditor = false;
            gridViewTimeSpanColumn1.FieldName = "TimeTrailerHistory";
            gridViewTimeSpanColumn1.FormatInfo = new System.Globalization.CultureInfo("en-GB");
            gridViewTimeSpanColumn1.FormatString = "dd:hh:mm:ss.fff";
            gridViewTimeSpanColumn1.HeaderText = "TimeTrailerHistory";
            gridViewTimeSpanColumn1.IsAutoGenerated = true;
            gridViewTimeSpanColumn1.Name = "TimeTrailerHistory";
            gridViewTimeSpanColumn1.Width = 113;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "Issue";
            gridViewTextBoxColumn2.HeaderText = "Issue";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "Issue";
            gridViewTextBoxColumn2.Width = 110;
            gridViewTextBoxColumn3.EnableExpressionEditor = false;
            gridViewTextBoxColumn3.FieldName = "Garage";
            gridViewTextBoxColumn3.HeaderText = "Garage";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "Garage";
            gridViewTextBoxColumn4.EnableExpressionEditor = false;
            gridViewTextBoxColumn4.FieldName = "Comment";
            gridViewTextBoxColumn4.HeaderText = "Comment";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "Comment";
            gridViewTextBoxColumn4.Width = 198;
            gridViewTextBoxColumn5.EnableExpressionEditor = false;
            gridViewTextBoxColumn5.FieldName = "UserCreation";
            gridViewTextBoxColumn5.HeaderText = "UserCreation";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Name = "UserCreation";
            gridViewTextBoxColumn5.Width = 83;
            gridViewDateTimeColumn2.EnableExpressionEditor = false;
            gridViewDateTimeColumn2.FieldName = "DateInsertion";
            gridViewDateTimeColumn2.HeaderText = "DateInsertion";
            gridViewDateTimeColumn2.IsAutoGenerated = true;
            gridViewDateTimeColumn2.Name = "DateInsertion";
            gridViewDateTimeColumn2.SortOrder = Telerik.WinControls.UI.RadSortOrder.Descending;
            gridViewDateTimeColumn2.Width = 86;
            this.radGridView1.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewDecimalColumn2,
            gridViewDecimalColumn3,
            gridViewDateTimeColumn1,
            gridViewTimeSpanColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewTextBoxColumn5,
            gridViewDateTimeColumn2});
            this.radGridView1.MasterTemplate.DataSource = this.bindingSource1;
            sortDescriptor1.Direction = System.ComponentModel.ListSortDirection.Descending;
            sortDescriptor1.PropertyName = "DateInsertion";
            this.radGridView1.MasterTemplate.SortDescriptors.AddRange(new Telerik.WinControls.Data.SortDescriptor[] {
            sortDescriptor1});
            this.radGridView1.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.radGridView1.Name = "radGridView1";
            this.radGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radGridView1.Size = new System.Drawing.Size(1087, 566);
            this.radGridView1.TabIndex = 0;
            // 
            // bindingSource1
            // 
            this.bindingSource1.DataMember = "TrailerHistory";
            this.bindingSource1.DataSource = this.axsTrailerHistory1;
            // 
            // axsTrailerHistory1
            // 
            this.axsTrailerHistory1.DataSetName = "axsTrailerHistory";
            this.axsTrailerHistory1.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // trailerHistoryTableAdapter1
            // 
            this.trailerHistoryTableAdapter1.ClearBeforeFill = true;
            // 
            // TrailerHistory
            // 
            this.behaviorManager1.SetBehaviors(this, new DevExpress.Utils.Behaviors.Behavior[] {
            ((DevExpress.Utils.Behaviors.Behavior)(DevExpress.Utils.Behaviors.Common.PersistenceBehavior.Create(typeof(DevExpress.Utils.BehaviorSource.PersistenceBehaviorSourceForForm), null, DevExpress.Utils.Behaviors.Common.Storage.Registry, DevExpress.Utils.DefaultBoolean.Default)))});
            this.ClientSize = new System.Drawing.Size(1087, 566);
            this.Controls.Add(this.radGridView1);
            this.IconOptions.SvgImage = ((DevExpress.Utils.Svg.SvgImage)(resources.GetObject("TrailerHistory.IconOptions.SvgImage")));
            this.Name = "TrailerHistory";
            this.Load += new System.EventHandler(this.TrailerHistory_Load_1);
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.axsTrailerHistory1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.behaviorManager1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private axsTrailerHistory axsTrailerHistory;
        private System.Windows.Forms.BindingSource trailerHistoryBindingSource;
        private DevExpress.XtraGrid.GridControl gridControl1;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private System.Windows.Forms.BindingSource axsTrailerHistoryBindingSource;
        private System.Windows.Forms.BindingSource trailerHistoryBindingSource1;
        private axsTrailerHistoryTableAdapters.TrailerHistoryTableAdapter trailerHistoryTableAdapter;
        private DevExpress.XtraGrid.Columns.GridColumn colHistId;
        private DevExpress.XtraGrid.Columns.GridColumn colTrailer;
        private DevExpress.XtraGrid.Columns.GridColumn colIdCO;
        private DevExpress.XtraGrid.Columns.GridColumn colidMovement;
        private DevExpress.XtraGrid.Columns.GridColumn colDateTrailerHistory;
        private DevExpress.XtraGrid.Columns.GridColumn colTimeTrailerHistory;
        private DevExpress.XtraGrid.Columns.GridColumn colIssue;
        private DevExpress.XtraGrid.Columns.GridColumn colGarage;
        private DevExpress.XtraGrid.Columns.GridColumn colComment;
        private DevExpress.XtraGrid.Columns.GridColumn colUserCreation;
        private DevExpress.XtraGrid.Columns.GridColumn colDateInsertion;
        private Telerik.WinControls.UI.RadGridView radGridView1;
        private axsTrailerHistory axsTrailerHistory1;
        private System.Windows.Forms.BindingSource bindingSource1;
        private axsTrailerHistoryTableAdapters.TrailerHistoryTableAdapter trailerHistoryTableAdapter1;
        private DevExpress.Utils.Behaviors.BehaviorManager behaviorManager1;
    }
}